#!/usr/bin/env bash
# Copies native Java plugins and XML configs into the generated Android project.
# Run after `npx cap sync android` — the android/ dir is gitignored and
# regenerated by `cap add android` on CI, so custom plugins and manifest
# overrides must be injected each time.
set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
APP_DIR="$SCRIPT_DIR/../android/app/src/main/java/ai/softshape/captain"
RES_XML_DIR="$SCRIPT_DIR/../android/app/src/main/res/xml"

# Copy Java plugins
mkdir -p "$APP_DIR"
cp "$SCRIPT_DIR/EscposPrintPlugin.java" "$APP_DIR/"
cp "$SCRIPT_DIR/MainActivity.java" "$APP_DIR/"

# Copy AndroidManifest.xml (adds INTERNET permission + cleartext traffic for TCP printing)
cp "$SCRIPT_DIR/AndroidManifest.xml" "$SCRIPT_DIR/../android/app/src/main/AndroidManifest.xml"

# Copy network security config (allows cleartext HTTP to edge server + TCP to printers)
mkdir -p "$RES_XML_DIR"
cp "$SCRIPT_DIR/network_security_config.xml" "$RES_XML_DIR/"

echo "[cap-sync-native] Copied EscposPrintPlugin.java, MainActivity.java, AndroidManifest.xml, network_security_config.xml to android project"
