#!/usr/bin/env bash
# Copies native Java plugins into the generated Android project.
# Run after `npx cap sync android` — the android/ dir is gitignored and
# regenerated by `cap add android` on CI, so custom plugins must be
# injected each time.
set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
APP_DIR="$SCRIPT_DIR/../android/app/src/main/java/ai/softshape/captain"

mkdir -p "$APP_DIR"
cp "$SCRIPT_DIR/EscposPrintPlugin.java" "$APP_DIR/"
cp "$SCRIPT_DIR/MainActivity.java" "$APP_DIR/"

echo "[cap-sync-native] Copied EscposPrintPlugin.java and MainActivity.java to android project"
