// ─────────────────────────────────────────────────────────────────────────────
// Print Offline — Cross-platform offline printing pipeline
// ─────────────────────────────────────────────────────────────────────────────
// Handles local printing when the backend socket is unavailable (offline mode).
// Dispatch strategy by platform:
//   1. Tauri desktop: window.__TAURI__.invoke('print_raw', { printerName, bytes })
//   2. Web/PWA with QZ Tray: sendToPrinter() from qzTray.js
//   3. Capacitor Android: Bluetooth/USB ESC/POS plugin (future)
//   4. iOS PWA: generate shareable PDF receipt
//   5. No printer: queue in offlinePrintJobs IndexedDB store for auto-print on reconnect
//
// Key functions:
//   - printOffline({ printerName, bytes, type, label }): dispatch print job
//   - flushOfflinePrintJobs(): retry all queued print jobs when back online
//   - detectPlatform(): identifies Tauri/Web/Android/iOS
//
// ESC/POS byte arrays are generated by the backend print routes and passed
// to this module for local dispatch.
// ─────────────────────────────────────────────────────────────────────────────

// ── Offline Print Pipeline ───────────────────────────────────────────────────
// Handles local printing when the backend socket is unavailable (offline mode).
// Dispatch strategy by platform:
//   1. Tauri desktop: window.__TAURI__.invoke('print_raw', { printerName, bytes })
//   2. Web/PWA with QZ Tray: sendToPrinter() from qzTray.js
//   3. Capacitor Android: Bluetooth/USB ESC/POS plugin (future)
//   4. iOS PWA: generate shareable PDF receipt
//   5. No printer: queue in offlinePrintJobs IndexedDB store for auto-print on reconnect

import { addOfflinePrintJob, getOfflinePrintJobs, updateOfflinePrintJob, getLocalPrinterMapping, setLocalPrinterMapping, getPrintAgentUrl, setPrintAgentUrl } from './offlineDB';
import { apiUrl, getAuthHeaders } from '../services/apiConfig';

// ── Platform detection ───────────────────────────────────────────────────────

function detectPlatform() {
  if (window.__TAURI__) return 'tauri';
  if (window.Capacitor?.isNativePlatform?.()) return 'capacitor';
  // iOS Safari standalone (PWA added to home screen)
  const ua = navigator.userAgent || '';
  const isIOS = /iPad|iPhone|iPod/.test(ua) || (navigator.platform === 'MacIntel' && navigator.maxTouchPoints > 1);
  if (isIOS && window.navigator.standalone) return 'ios-pwa';
  if (isIOS) return 'ios-browser';
  return 'web';
}

// ── Printer config ───────────────────────────────────────────────────────────

async function getPrinterMapping() {
  try {
    return await getLocalPrinterMapping();
  } catch {
    // Fallback to legacy localStorage mapping if IndexedDB is unavailable
    try {
      const stored = localStorage.getItem('agent_printer_mapping');
      return stored ? JSON.parse(stored) : {};
    } catch {
      return {};
    }
  }
}

function resolvePrinter(jobType, mapping) {
  // Fall back to mapping
  if (jobType === 'KOT' || jobType === 'CANCEL_KOT') return mapping.kitchen;
  if (jobType === 'BAR_KOT') return mapping.bar;
  if (jobType === 'FINAL_BILL' || jobType === 'BILL' || jobType === 'VOUCHER' || jobType === 'EXPENDITURE') return mapping.bill;
  if (jobType === 'TABLE_SWAP') return mapping.kitchen;
  return null;
}

// ── ESC/POS generation helpers ───────────────────────────────────────────────

function textToEscpos(text) {
  // Simple text-to-ESC/POS: just encode the raw text.
  // The backend normally generates proper ESC/POS with formatting,
  // but for offline we send plain text with basic line breaks.
  // Real ESC/POS commands can be added here later if needed.
  const encoder = new TextEncoder();
  return encoder.encode(text);
}

function buildBillText({ tableNumber, items, subtotal, discount, cgst, sgst, grandTotal, roundOff, billNumber, restaurantName, restaurant }) {
  const lines = [];
  const W = 32; // 32 chars wide for 58mm paper (48 for 80mm)
  const center = (s) => {
    const pad = Math.max(0, Math.floor((W - s.length) / 2));
    return ' '.repeat(pad) + s;
  };
  const line = '-'.repeat(W);

  const headerName = restaurantName || restaurant?.receiptHeader || restaurant?.name;
  if (headerName) lines.push(center(headerName));
  if (restaurant?.receiptSubHeader) lines.push(center(restaurant.receiptSubHeader));
  if (restaurant?.address) lines.push(center(restaurant.address));
  if (restaurant?.phone) lines.push(center(`Phone: ${restaurant.phone}`));
  lines.push(center('*** TAX INVOICE ***'));
  lines.push(line);
  if (billNumber) lines.push(`Bill: ${billNumber}`);
  if (tableNumber) lines.push(`Table: ${tableNumber}`);
  lines.push(`Date: ${new Date().toLocaleString('en-IN')}`);
  lines.push(line);

  for (const item of items) {
    const name = (item.name || item.n || '').substring(0, 20);
    const qty = String(item.quantity || item.q || 1).padStart(3);
    const price = Math.round(Number(item.price || item.p || 0)).toFixed(0).padStart(7);
    lines.push(`${name}${qty}x${price}`);
  }

  lines.push(line);
  const rawSub = Number(subtotal || 0);
  lines.push(`Subtotal:        Rs.${Math.round(rawSub).toFixed(0)}`);
  if (cgst) lines.push(`CGST:            Rs.${Number(cgst).toFixed(2)}`);
  if (sgst) lines.push(`SGST:            Rs.${Number(sgst).toFixed(2)}`);
  if (discount && Number(discount.amount || 0) > 0) {
    const discAmt = Math.round(Number(discount.amount || 0));
    lines.push(`Discount (${Math.round(Number(discount.percent || 0)).toFixed(0)}%): -Rs.${discAmt.toFixed(0)}`);
  }
  lines.push(line);
  if (roundOff && Number(roundOff) !== 0) {
    const roVal = Number(roundOff);
    lines.push(`Round Off:       Rs.${roVal > 0 ? '+' : ''}${roVal.toFixed(2)}`);
  }
  lines.push(`GRAND TOTAL:     Rs.${Math.round(Number(grandTotal || 0)).toFixed(0)}`);
  lines.push(line);
  lines.push(center('Thank You!'));
  lines.push('\n\n\n');

  return lines.join('\n');
}

function buildKotText({ tableNumber, items, kotNumber, restaurantName, captainName }) {
  const lines = [];
  const W = 32;
  const center = (s) => {
    const pad = Math.max(0, Math.floor((W - s.length) / 2));
    return ' '.repeat(pad) + s;
  };
  const line = '-'.repeat(W);

  if (restaurantName) lines.push(center(restaurantName));
  lines.push(center('*** K O T ***'));
  lines.push(line);
  if (kotNumber) lines.push(`KOT: ${kotNumber}`);
  if (tableNumber) lines.push(`Table: ${tableNumber}`);
  if (captainName) lines.push(`Captain: ${captainName}`);
  lines.push(`Time: ${new Date().toLocaleTimeString('en-IN')}`);
  lines.push(line);

  for (const item of items) {
    const name = (item.name || item.n || '').substring(0, 24);
    const qty = String(item.quantity || item.q || 1).padStart(3);
    lines.push(`${qty}x  ${name}`);
    if (item.notes) lines.push(`    * ${item.notes}`);
  }

  lines.push(line);
  lines.push('\n\n\n');

  return lines.join('\n');
}

// ── Multi-URL Print Agent discovery ──────────────────────────────────────────

let _cachedAgentUrls = null;
let _lastDiscoveryTime = 0;
const DISCOVERY_CACHE_MS = 30_000;

/**
 * Build a list of candidate Print Agent URLs to try, in priority order:
 *   1. User-configured URL from IndexedDB (manual setting)
 *   2. Backend-reported LAN IP (fetched from /api/print/agent-endpoint)
 *   3. localStorage cache of last-known working URL
 *   4. localhost fallback (same-machine only)
 */
async function discoverPrintAgentUrls() {
  if (_cachedAgentUrls && Date.now() - _lastDiscoveryTime < DISCOVERY_CACHE_MS) {
    return _cachedAgentUrls;
  }

  const urls = [];
  const seen = new Set();

  function add(url) {
    if (!url) return;
    const normalized = url.replace(/\/+$/, '');
    if (!seen.has(normalized)) {
      seen.add(normalized);
      urls.push(normalized);
    }
  }

  // 1. User-configured URL
  const configuredUrl = await getPrintAgentUrl();
  if (configuredUrl && configuredUrl !== 'http://localhost:3100') {
    add(configuredUrl);
  }

  // 2. Backend-reported URL (from Print Agent registration/heartbeat)
  try {
    const controller = new AbortController();
    const timeout = setTimeout(() => controller.abort(), 300);
    const res = await fetch(apiUrl('/api/print/agent-endpoint'), {
      method: 'GET',
      headers: getAuthHeaders(),
      signal: controller.signal,
    });
    clearTimeout(timeout);
    if (res.ok) {
      const data = await res.json();
      if (data.httpUrl) add(data.httpUrl);
      if (data.lanIp) add(`http://${data.lanIp}:3100`);
      if (data.printerMapping && Object.keys(data.printerMapping).length > 0) {
        setLocalPrinterMapping(data.printerMapping).catch(() => {});
      }
    }
  } catch {
    // Backend unreachable — skip
  }

  // 3. localStorage cache of last-known working URL
  try {
    const cached = localStorage.getItem('last_working_print_agent_url');
    if (cached) add(cached);
  } catch { /* ignore */ }

  // 4. localhost fallback (works when running on the same machine as Print Agent)
  add('http://localhost:3100');

  _cachedAgentUrls = urls;
  _lastDiscoveryTime = Date.now();
  return urls;
}

/**
 * Try all candidate Print Agent URLs in parallel and return the first that succeeds.
 * Each URL gets a 1.5s timeout — if the Print Agent is unreachable, all URLs fail
 * in parallel so the total wait is ~1.5s instead of 3s × N (sequential).
 * Returns the working URL or null if all fail.
 */
async function tryPrintAgentUrls(body, jobType) {
  const urls = await discoverPrintAgentUrls();
  if (urls.length === 0) return null;

  const tryUrl = async (url) => {
    const controller = new AbortController();
    const timeout = setTimeout(() => controller.abort(), 1500);
    try {
      const res = await fetch(`${url}/print`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(body),
        signal: controller.signal,
      });
      clearTimeout(timeout);
      if (res.ok) return url;
    } catch (err) {
      clearTimeout(timeout);
      if (err.name !== 'AbortError') {
        console.log(`[printOffline] Print Agent not reachable at ${url}:`, err.message);
      } else {
        console.log(`[printOffline] Print Agent timeout at ${url}`);
      }
    }
    return null;
  };

  // First-success-wins: resolve as soon as any URL succeeds, don't wait for others to timeout
  const workingUrl = await new Promise((resolve) => {
    let settled = false;
    let remaining = urls.length;
    urls.forEach(async (url) => {
      const result = await tryUrl(url);
      if (!settled && result) {
        settled = true;
        resolve(result);
      } else {
        remaining--;
        if (remaining === 0 && !settled) {
          resolve(null);
        }
      }
    });
  });

  if (workingUrl) {
    console.log(`[printOffline] Printed [${jobType}] via Print Agent at ${workingUrl}`);
    try {
      localStorage.setItem('last_working_print_agent_url', workingUrl);
      if (workingUrl !== 'http://localhost:3100') {
        await setPrintAgentUrl(workingUrl);
      }
    } catch { /* ignore */ }
  }

  return workingUrl;
}

// ── Debug log (visible in UI) ─────────────────────────────────────────────────

const offlinePrintLog = [];

export function getOfflinePrintLog() {
  return offlinePrintLog;
}

function logOfflinePrint(entry) {
  offlinePrintLog.push({ timestamp: Date.now(), ...entry });
  if (offlinePrintLog.length > 50) offlinePrintLog.shift();
  console.log('[printOffline]', entry.status, entry.message, entry.detail || '');
}

// ── Print dispatch ───────────────────────────────────────────────────────────

/**
 * Attempt to print a job locally based on the current platform.
 * Returns true if printed, false if queued.
 *
 * When escposData is provided (from buildFoodKOT/buildLiquorKOT), it is sent
 * to the Print Agent as the new { type, printerName, escposData, eventId } contract.
 * When not provided (backward compat with existing offline calls), falls back to
 * the legacy { jobType, printerName, text, bytes } contract.
 *
 * @param {{ jobType?: string, type?: string, text?: string, escposData?: object[], data?: object, printerName?: string, eventId?: string }} job
 * @returns {Promise<{ printed: boolean, queued: boolean, error?: string }>}
 */
export async function printLocal(job) {
  const platform = detectPlatform();
  const mapping = await getPrinterMapping();
  const jobType = job.type || job.jobType;
  const printerName = job.printerName || resolvePrinter(jobType, mapping);

  logOfflinePrint({ status: 'start', message: `${jobType} on ${platform}`, detail: `mapped=${printerName || 'none'}` });

  // Generate text content if not provided (legacy fallback)
  const text = job.text || (jobType === 'FINAL_BILL' || jobType === 'BILL'
    ? buildBillText(job.data || {})
    : jobType === 'KOT' || jobType === 'BAR_KOT'
    ? buildKotText(job.data || {})
    : JSON.stringify(job.data || {}));
  const bytes = Array.from(textToEscpos(text));

  // ── Primary: local Print Agent HTTP endpoint (multi-URL discovery) ──
  // Try multiple candidate URLs (configured, backend-reported, cached, localhost)
  // to support captain on WiFi/LAN (direct HTTP) and mobile data (socket fallback).
  const body = job.escposData
    ? {
        type: jobType,
        printerName: printerName || undefined,
        escposData: job.escposData,
        eventId: job.eventId || undefined,
        data: job.data || {},
      }
    : {
        jobType,
        printerName: printerName || undefined,
        text,
        bytes,
        data: job.data || {},
      };

  const workingUrl = await tryPrintAgentUrls(body, jobType);
  if (workingUrl) {
    logOfflinePrint({ status: 'success', message: 'Print Agent succeeded', detail: workingUrl });
    return { printed: true, queued: false };
  }
  logOfflinePrint({ status: 'error', message: 'Print Agent unreachable', detail: 'queued' });

  // ── Web with QZ Tray: try direct print ──
  if (platform === 'web') {
    if (!printerName) {
      return await queuePrintJob(job, text, 'No printer mapped');
    }
    try {
      const { sendToPrinter } = await import('./qzTray');
      const printData = [{ type: 'raw', format: 'plain', data: text }];
      await sendToPrinter(printerName, printData);
      logOfflinePrint({ status: 'success', message: 'QZ Tray succeeded', detail: printerName });
      return { printed: true, queued: false };
    } catch (err) {
      logOfflinePrint({ status: 'error', message: 'QZ Tray failed', detail: err?.message || String(err) });
      return await queuePrintJob(job, text, err?.message || String(err));
    }
  }

  // ── iOS PWA: generate shareable PDF ──
  if (platform === 'ios-pwa' || platform === 'ios-browser') {
    try {
      await shareAsPDF(job, text);
      logOfflinePrint({ status: 'success', message: 'iOS PDF share succeeded' });
      return { printed: true, queued: false };
    } catch (err) {
      logOfflinePrint({ status: 'error', message: 'iOS PDF share failed', detail: err?.message || String(err) });
      return await queuePrintJob(job, text, err?.message || String(err));
    }
  }

  // ── Capacitor Android: ESC/POS via native plugin ──
  if (platform === 'capacitor') {
    try {
      const { registerPlugin } = await import('@capacitor/core');
      const EscposPrint = registerPlugin('EscposPrint');

      // Try network printer first if configured
      const networkPrinterIp = localStorage.getItem('offline_network_printer_ip');
      if (networkPrinterIp) {
        const networkPort = parseInt(localStorage.getItem('offline_network_printer_port') || '9100', 10);
        const bytes = Array.from(textToEscpos(text));
        await EscposPrint.printNetwork({ ip: networkPrinterIp, port: networkPort, bytes });
        logOfflinePrint({ status: 'success', message: 'Capacitor network print succeeded', detail: `${networkPrinterIp}:${networkPort}` });
        return { printed: true, queued: false };
      }

      // Try Bluetooth/raw print
      if (printerName) {
        const bytes = Array.from(textToEscpos(text));
        await EscposPrint.printRaw({ printerName, bytes });
        logOfflinePrint({ status: 'success', message: 'Capacitor raw print succeeded', detail: printerName });
        return { printed: true, queued: false };
      }

      return await queuePrintJob(job, text, 'No printer configured for Android');
    } catch (err) {
      logOfflinePrint({ status: 'error', message: 'Capacitor print failed', detail: err?.message || String(err) });
      return await queuePrintJob(job, text, err?.message || String(err));
    }
  }

  // ── Unknown platform: queue ──
  logOfflinePrint({ status: 'error', message: 'Unknown platform', detail: platform });
  return await queuePrintJob(job, text, 'Unknown platform — cannot print locally');
}

// ── Queue management ─────────────────────────────────────────────────────────

async function queuePrintJob(job, text, reason) {
  const id = `offline-print-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
  await addOfflinePrintJob({
    id,
    jobType: job.jobType,
    orderId: job.data?.orderId || null,
    requestId: job.data?.requestId || null,
    text,
    data: job.data || {},
    printerName: job.printerName || null,
    status: 'pending',
    failReason: reason,
    createdAt: Date.now(),
  });
  logOfflinePrint({ status: 'queued', message: `${job.jobType} queued`, detail: reason });
  return { printed: false, queued: true, error: reason };
}

/**
 * Process all queued print jobs. Called when connectivity is restored
 * or when a printer becomes available.
 */
export async function flushQueuedPrintJobs() {
  const jobs = await getOfflinePrintJobs();
  logOfflinePrint({ status: 'flush', message: 'Flush started', detail: `${jobs.length} jobs` });
  if (!jobs || jobs.length === 0) return { flushed: 0, failed: 0 };

  let flushed = 0;
  let failed = 0;

  for (const job of jobs) {
    if (job.status !== 'pending') continue;

    try {
      const result = await printLocal({
        jobType: job.jobType,
        text: job.text,
        data: job.data,
        printerName: job.printerName,
      });

      if (result.printed) {
        await updateOfflinePrintJob(job.id, { status: 'printed', printedAt: Date.now() });
        flushed++;
      } else {
        // Still can't print — leave as pending
        failed++;
      }
    } catch (err) {
      logOfflinePrint({ status: 'error', message: 'Flush job failed', detail: err?.message || String(err) });
      failed++;
    }
  }

  logOfflinePrint({ status: 'flush', message: 'Flush done', detail: `${flushed} ok, ${failed} failed` });
  return { flushed, failed };
}

// ── iOS PDF sharing ──────────────────────────────────────────────────────────

async function shareAsPDF(job, text) {
  // Create a simple printable HTML document and open in new window for AirPrint
  const html = `
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>${job.jobType === 'KOT' ? 'KOT' : 'Bill'}</title>
<style>
  body { font-family: 'Courier New', monospace; font-size: 12px; margin: 10px; white-space: pre; }
  @media print { body { margin: 0; } }
</style>
</head>
<body>${text.replace(/</g, '&lt;')}</body>
</html>`;

  const blob = new Blob([html], { type: 'text/html' });
  const url = URL.createObjectURL(blob);
  const win = window.open(url, '_blank');

  if (win) {
    // Trigger print dialog after a short delay
    setTimeout(() => {
      win.print();
      URL.revokeObjectURL(url);
    }, 500);
  } else {
    // Pop-up blocked — try Web Share API as fallback
    if (navigator.share) {
      const file = new File([blob], `${job.jobType}-${Date.now()}.html`, { type: 'text/html' });
      await navigator.share({ files: [file], title: job.jobType });
    } else {
      throw new Error('Cannot open print window or share — pop-up blocked');
    }
  }
}

// ── Public API ───────────────────────────────────────────────────────────────

export { detectPlatform, buildBillText, buildKotText, getPrinterMapping, resolvePrinter, discoverPrintAgentUrls };

/**
 * Manual test entry point for the offline print pipeline.
 * Run in the browser console: `window.testOfflinePrint()`
 */
export async function testOfflinePrintPipeline() {
  const platform = detectPlatform();
  const mapping = await getPrinterMapping();
  const report = {
    platform,
    hasPrinterMapping: Object.keys(mapping).length > 0,
    mapping,
    queued: false,
    flushed: 0,
    failed: 0,
    errors: [],
  };

  try {
    const result = await printLocal({
      jobType: 'FINAL_BILL',
      data: {
        tableNumber: 'TEST',
        items: [{ name: 'Test Item', quantity: 1, price: 100 }],
        subtotal: 100,
        grandTotal: 100,
        billNumber: 'TEST-001',
        restaurantName: 'Offline Print Test',
      },
    });
    report.queued = result.queued;
  } catch (err) {
    report.errors.push(`Queue failed: ${err.message}`);
  }

  try {
    const flush = await flushOfflinePrintJobs();
    report.flushed = flush.flushed;
    report.failed = flush.failed;
  } catch (err) {
    report.errors.push(`Flush failed: ${err.message}`);
  }

  console.log('[printOffline] Test report:', report);
  return report;
}

if (typeof window !== 'undefined') {
  window.testOfflinePrint = testOfflinePrintPipeline;
}
