#!/usr/bin/env bash
# Copies Android-only native sources into the generated Capacitor project.
# The android/ directory is generated by Capacitor and must not be hand-edited.
set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
APP_DIR="$SCRIPT_DIR/../android/app/src/main/java/ai/softshape/cashier"

mkdir -p "$APP_DIR"
cp "$SCRIPT_DIR/LocalPosDatabasePlugin.java" "$APP_DIR/"
cp "$SCRIPT_DIR/MainActivity.java" "$APP_DIR/"
cp "$SCRIPT_DIR/AndroidManifest.xml" "$SCRIPT_DIR/../android/app/src/main/AndroidManifest.xml"

echo "[cap-sync-native] Copied Android Local POS database plugin and manifest"
