const round2 = (n) => Math.round((Number(n || 0) + Number.EPSILON) * 100) / 100;
const inr = (n) => '₹' + Number(n).toLocaleString('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 });
const inrPlain = (n) => Number(n).toLocaleString('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 });

const flex = { display: 'flex' };
const flexCol = { display: 'flex', flexDirection: 'column' };
const flexCenter = { display: 'flex', alignItems: 'center', justifyContent: 'center' };
const flexBetween = { display: 'flex', alignItems: 'center', justifyContent: 'space-between' };
const flexStartBetween = { display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between' };

function MetaItem({ label, children }) {
  return (
    <div style={{ ...flex, alignItems: 'center', gap: '12px' }}>
      <div style={{ ...flexCenter, height: '44px', width: '44px', borderRadius: '50%', background: '#FEF2F2' }}>
        <div style={{ width: '8px', height: '8px', borderRadius: '50%', background: '#EF4444' }} />
      </div>
      <div style={flexCol}>
        <div style={{ fontSize: '10px', fontWeight: 700, letterSpacing: '0.05em', color: '#9CA3AF' }}>{label}</div>
        <div style={{ fontSize: '14px', fontWeight: 700, color: '#1E293B' }}>{children}</div>
      </div>
    </div>
  );
}

export default function PurchaseReportTemplate({ data, logoSrc }) {
  const { restaurantName, date, weekday, rows, remarks, generatedOn, generatedBy } = data;

  const validRows = rows.filter((r) => r.itemName?.trim() && (parseFloat(r.quantity) || 0) > 0);
  const totalItems = validRows.length;
  const totalAmount = round2(validRows.reduce((sum, r) => sum + round2(r.quantity) * round2(r.unitPrice), 0));

  const thBase = {
    padding: '12px 16px',
    fontSize: '10px',
    fontWeight: 700,
    textTransform: 'uppercase',
    letterSpacing: '0.05em',
    color: '#6B7280',
  };

  const tdBase = {
    padding: '12px 16px',
    fontSize: '14px',
  };

  return (
    <div
      id="purchase-report"
      style={{
        width: '900px',
        margin: '0 auto',
        padding: '32px',
        boxSizing: 'border-box',
        fontFamily: "'Inter', 'Helvetica Neue', Arial, sans-serif",
        background: '#FFFFFF',
        color: '#1E293B',
      }}
    >
      {/* ── Header ─────────────────────────────────────────────────── */}
      <div style={flexStartBetween}>
        <div style={{ ...flex, alignItems: 'center', gap: '12px' }}>
          <div style={{ ...flexCenter, height: '56px', width: '56px', borderRadius: '12px', background: '#E63946' }}>
            <img src={logoSrc} alt="Softshape" style={{ height: '32px', width: '32px', objectFit: 'contain' }} />
          </div>
          <div style={flexCol}>
            <div style={{ fontSize: '20px', fontWeight: 900, color: '#0F172A' }}>Softshape</div>
            <div style={{ fontSize: '9px', fontWeight: 700, letterSpacing: '0.15em', color: '#9CA3AF' }}>
              THE AI OPERATING SYSTEM FOR RESTAURANTS
            </div>
          </div>
        </div>
        <div style={{ textAlign: 'right' }}>
          <h1 style={{ fontSize: '30px', fontWeight: 900, margin: 0 }}>
            <span style={{ color: '#0F172A' }}>DAILY </span>
            <span style={{ color: '#E63946' }}>PURCHASE ENTRY</span>
          </h1>
        </div>
      </div>
      <div style={{ marginTop: '16px', height: '3px', width: '100%', background: '#E63946' }} />

      {/* ── Meta row ───────────────────────────────────────────────── */}
      <div style={{ marginTop: '24px', ...flexStartBetween }}>
        <div style={{ ...flex, gap: '32px' }}>
          <MetaItem label="OUTLET">{restaurantName}</MetaItem>
          <MetaItem label="DATE">
            {date}
            {weekday && <div style={{ fontSize: '12px', fontWeight: 500, color: '#9CA3AF' }}>{weekday}</div>}
          </MetaItem>
          <MetaItem label="TOTAL ITEMS">{totalItems} Items</MetaItem>
        </div>
        <div style={{ textAlign: 'right', fontSize: '11px', lineHeight: '20px', color: '#6B7280' }}>
          <div><span style={{ fontWeight: 700, color: '#9CA3AF' }}>GENERATED ON: </span>{generatedOn}</div>
          <div><span style={{ fontWeight: 700, color: '#9CA3AF' }}>GENERATED BY: </span>{generatedBy}</div>
        </div>
      </div>

      {/* ── Purchase Items Table ───────────────────────────────────── */}
      <div style={{ marginTop: '24px', borderRadius: '12px', overflow: 'hidden', border: '1px solid #E5E7EB' }}>
        <div style={{ ...flex, alignItems: 'center', gap: '8px', padding: '10px 16px', background: '#0F172A' }}>
          <span style={{ fontSize: '12px', fontWeight: 700, letterSpacing: '0.05em', color: '#FFFFFF' }}>PURCHASE ITEMS</span>
        </div>
        <table style={{ width: '100%', textAlign: 'left', fontSize: '14px', borderCollapse: 'collapse' }}>
          <thead>
            <tr style={{ background: '#F9FAFB' }}>
              <th style={{ ...thBase, textAlign: 'center', width: '40px' }}>#</th>
              <th style={{ ...thBase, textAlign: 'left' }}>Item Name</th>
              <th style={{ ...thBase, textAlign: 'center', width: '70px' }}>Qty</th>
              <th style={{ ...thBase, textAlign: 'center', width: '70px' }}>Unit</th>
              <th style={{ ...thBase, textAlign: 'right', width: '100px' }}>Rate (₹)</th>
              <th style={{ ...thBase, textAlign: 'right', width: '120px' }}>Amount (₹)</th>
            </tr>
          </thead>
          <tbody>
            {validRows.map((row, idx) => {
              const amount = round2(row.quantity) * round2(row.unitPrice);
              return (
                <tr key={idx} style={{ background: idx % 2 === 0 ? '#FFFFFF' : '#F9FAFB', borderBottom: '1px solid #F3F4F6' }}>
                  <td style={{ ...tdBase, textAlign: 'center', fontWeight: 600, color: '#6B7280' }}>{idx + 1}</td>
                  <td style={{ ...tdBase, fontWeight: 700, color: '#1E293B', wordBreak: 'break-word', maxWidth: '380px' }}>{row.itemName}</td>
                  <td style={{ ...tdBase, textAlign: 'center', fontWeight: 600, color: '#334155' }}>{Number(row.quantity)}</td>
                  <td style={{ ...tdBase, textAlign: 'center', fontWeight: 600, color: '#6B7280' }}>{row.unit || '—'}</td>
                  <td style={{ ...tdBase, textAlign: 'right', fontWeight: 600, color: '#334155' }}>{inrPlain(round2(row.unitPrice))}</td>
                  <td style={{ ...tdBase, textAlign: 'right', fontWeight: 700, color: '#1E293B' }}>{inrPlain(amount)}</td>
                </tr>
              );
            })}
          </tbody>
        </table>
      </div>

      {/* ── Remarks / Notes ────────────────────────────────────────── */}
      {remarks && (
        <div style={{ marginTop: '16px', borderRadius: '12px', border: '1px solid #BBF7D0', background: '#F0FDF4', padding: '16px' }}>
          <div style={{ marginBottom: '4px', fontSize: '10px', fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.05em', color: '#16A34A' }}>Notes / Remarks</div>
          <div style={{ fontSize: '14px', fontWeight: 600, color: '#166534', lineHeight: 1.6 }}>{remarks}</div>
        </div>
      )}

      {/* ── Footer band ────────────────────────────────────────────── */}
      <div style={{ marginTop: '24px', ...flexBetween, borderRadius: '12px', padding: '20px', background: '#0F172A' }}>
        <div style={flexCol}>
          <div style={{ fontSize: '10px', fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.05em', color: '#9CA3AF' }}>Total Purchase Amount</div>
          <div style={{ fontSize: '30px', fontWeight: 900, color: '#4ADE80' }}>{inr(totalAmount)}</div>
          <div style={{ marginTop: '4px', fontSize: '10px', color: '#9CA3AF' }}>{totalItems} item{totalItems !== 1 ? 's' : ''} purchased</div>
        </div>
        <div style={{ ...flex, gap: '32px', textAlign: 'center', fontSize: '10px', color: '#D1D5DB' }}>
          <div style={flexCol}>
            <div style={{ marginBottom: '16px', width: '96px', borderBottom: '1px solid #6B7280' }} />
            PREPARED BY<br /><span style={{ color: '#6B7280' }}>(Signature)</span>
          </div>
          <div style={flexCol}>
            <div style={{ marginBottom: '16px', width: '96px', borderBottom: '1px solid #6B7280' }} />
            VERIFIED BY<br /><span style={{ color: '#6B7280' }}>(Signature)</span>
          </div>
        </div>
      </div>

      <div style={{ marginTop: '12px', textAlign: 'center', fontSize: '10px', color: '#9CA3AF' }}>
        Softshape AI - software that shapes your business
      </div>
    </div>
  );
}
