import { Store, Calendar, Package, ClipboardList } from 'lucide-react';

const round2 = (n) => Math.round((Number(n || 0) + Number.EPSILON) * 100) / 100;
const inr = (n) => '₹' + Number(n).toLocaleString('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 });
const inrPlain = (n) => Number(n).toLocaleString('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 });

function MetaItem({ icon: Icon, label, children }) {
  return (
    <div className="flex items-center gap-3">
      <div className="flex h-11 w-11 items-center justify-center rounded-full" style={{ background: '#FEF2F2' }}>
        <Icon size={20} style={{ color: '#EF4444' }} />
      </div>
      <div>
        <div className="text-[10px] font-bold tracking-wide" style={{ color: '#9CA3AF' }}>{label}</div>
        <div className="text-sm font-bold" style={{ color: '#1E293B' }}>{children}</div>
      </div>
    </div>
  );
}

export default function PurchaseReportTemplate({ data, logoSrc }) {
  const { restaurantName, date, weekday, rows, remarks, generatedOn, generatedBy } = data;

  const validRows = rows.filter((r) => r.itemName?.trim() && (parseFloat(r.quantity) || 0) > 0);
  const totalItems = validRows.length;
  const totalAmount = round2(validRows.reduce((sum, r) => sum + round2(r.quantity) * round2(r.unitPrice), 0));

  return (
    <div
      id="purchase-report"
      className="mx-auto w-[900px] p-8 font-sans"
      style={{ fontFamily: "'Inter', 'Helvetica Neue', Arial, sans-serif", background: '#FFFFFF', color: '#1E293B' }}
    >
      {/* ── Header ─────────────────────────────────────────────────── */}
      <div className="flex items-start justify-between">
        <div className="flex items-center gap-3">
          <div className="flex h-14 w-14 items-center justify-center rounded-xl" style={{ background: '#E63946' }}>
            <img src={logoSrc} alt="Softshape" className="h-8 w-8 object-contain" />
          </div>
          <div>
            <div className="text-xl font-black">
              <span style={{ color: '#0F172A' }}>Softshape</span>
            </div>
            <div className="text-[9px] font-bold tracking-widest" style={{ color: '#9CA3AF' }}>
              THE AI OPERATING SYSTEM FOR RESTAURANTS
            </div>
          </div>
        </div>
        <div className="text-right">
          <h1 className="text-3xl font-black">
            <span style={{ color: '#0F172A' }}>DAILY </span>
            <span style={{ color: '#E63946' }}>PURCHASE ENTRY</span>
          </h1>
        </div>
      </div>
      <div className="mt-4 h-[3px] w-full" style={{ background: '#E63946' }} />

      {/* ── Meta row ───────────────────────────────────────────────── */}
      <div className="mt-6 flex items-start justify-between">
        <div className="flex gap-8">
          <MetaItem icon={Store} label="OUTLET">{restaurantName}</MetaItem>
          <MetaItem icon={Calendar} label="DATE">
            {date}
            {weekday && <div className="text-xs font-medium" style={{ color: '#9CA3AF' }}>{weekday}</div>}
          </MetaItem>
          <MetaItem icon={Package} label="TOTAL ITEMS">{totalItems} Items</MetaItem>
        </div>
        <div className="text-right text-[11px] leading-5" style={{ color: '#6B7280' }}>
          <div><span className="font-bold" style={{ color: '#9CA3AF' }}>GENERATED ON: </span>{generatedOn}</div>
          <div><span className="font-bold" style={{ color: '#9CA3AF' }}>GENERATED BY: </span>{generatedBy}</div>
        </div>
      </div>

      {/* ── Purchase Items Table ───────────────────────────────────── */}
      <div className="mt-6 overflow-hidden rounded-xl border" style={{ borderColor: '#E5E7EB' }}>
        <div className="flex items-center gap-2 px-4 py-2.5" style={{ background: '#0F172A' }}>
          <ClipboardList size={16} style={{ color: '#FFFFFF' }} />
          <span className="text-xs font-bold tracking-wide" style={{ color: '#FFFFFF' }}>PURCHASE ITEMS</span>
        </div>
        <table className="w-full text-left text-sm" style={{ borderCollapse: 'collapse' }}>
          <thead>
            <tr style={{ background: '#F9FAFB' }}>
              <th className="px-4 py-3 text-center text-[10px] font-bold uppercase tracking-wide" style={{ color: '#6B7280', width: '40px' }}>#</th>
              <th className="px-4 py-3 text-left text-[10px] font-bold uppercase tracking-wide" style={{ color: '#6B7280' }}>Item Name</th>
              <th className="px-4 py-3 text-center text-[10px] font-bold uppercase tracking-wide" style={{ color: '#6B7280', width: '70px' }}>Qty</th>
              <th className="px-4 py-3 text-center text-[10px] font-bold uppercase tracking-wide" style={{ color: '#6B7280', width: '70px' }}>Unit</th>
              <th className="px-4 py-3 text-right text-[10px] font-bold uppercase tracking-wide" style={{ color: '#6B7280', width: '100px' }}>Rate (₹)</th>
              <th className="px-4 py-3 text-right text-[10px] font-bold uppercase tracking-wide" style={{ color: '#6B7280', width: '120px' }}>Amount (₹)</th>
            </tr>
          </thead>
          <tbody>
            {validRows.map((row, idx) => {
              const amount = round2(row.quantity) * round2(row.unitPrice);
              return (
                <tr key={idx} style={{ background: idx % 2 === 0 ? '#FFFFFF' : '#F9FAFB', borderBottom: '1px solid #F3F4F6' }}>
                  <td className="px-4 py-3 text-center font-semibold" style={{ color: '#6B7280' }}>{idx + 1}</td>
                  <td className="px-4 py-3 font-bold" style={{ color: '#1E293B' }}>{row.itemName}</td>
                  <td className="px-4 py-3 text-center font-semibold" style={{ color: '#334155' }}>{Number(row.quantity)}</td>
                  <td className="px-4 py-3 text-center font-semibold" style={{ color: '#6B7280' }}>{row.unit || '—'}</td>
                  <td className="px-4 py-3 text-right font-semibold" style={{ color: '#334155' }}>{inrPlain(round2(row.unitPrice))}</td>
                  <td className="px-4 py-3 text-right font-bold" style={{ color: '#1E293B' }}>{inrPlain(amount)}</td>
                </tr>
              );
            })}
          </tbody>
        </table>
      </div>

      {/* ── Remarks / Notes ────────────────────────────────────────── */}
      {remarks && (
        <div className="mt-4 rounded-xl border p-4" style={{ borderColor: '#BBF7D0', background: '#F0FDF4' }}>
          <div className="mb-1 text-[10px] font-bold uppercase tracking-wide" style={{ color: '#16A34A' }}>Notes / Remarks</div>
          <div className="text-sm font-semibold" style={{ color: '#166534', lineHeight: 1.6 }}>{remarks}</div>
        </div>
      )}

      {/* ── Footer band ────────────────────────────────────────────── */}
      <div className="mt-6 flex items-center justify-between rounded-xl p-5" style={{ background: '#0F172A' }}>
        <div>
          <div className="text-[10px] font-bold uppercase tracking-wide" style={{ color: '#9CA3AF' }}>Total Purchase Amount</div>
          <div className="text-3xl font-black" style={{ color: '#4ADE80' }}>{inr(totalAmount)}</div>
          <div className="mt-1 text-[10px]" style={{ color: '#9CA3AF' }}>{totalItems} item{totalItems !== 1 ? 's' : ''} purchased</div>
        </div>
        <div className="flex gap-8 text-center text-[10px]" style={{ color: '#D1D5DB' }}>
          <div>
            <div className="mb-4 w-24 border-b" style={{ borderColor: '#6B7280' }} />
            PREPARED BY<br /><span style={{ color: '#6B7280' }}>(Signature)</span>
          </div>
          <div>
            <div className="mb-4 w-24 border-b" style={{ borderColor: '#6B7280' }} />
            VERIFIED BY<br /><span style={{ color: '#6B7280' }}>(Signature)</span>
          </div>
        </div>
      </div>

      <div className="mt-3 text-center text-[10px]" style={{ color: '#9CA3AF' }}>
        Softshape AI - software that shapes your business
      </div>
    </div>
  );
}
