const round2 = (n) => Math.round((Number(n || 0) + Number.EPSILON) * 100) / 100;
const inr = (n) => '₹' + Number(n).toLocaleString('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 });
const inrPlain = (n) => Number(n).toLocaleString('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 });

const flex = { display: 'flex' };
const flexCol = { display: 'flex', flexDirection: 'column' };
const flexCenter = { display: 'flex', alignItems: 'center', justifyContent: 'center' };
const flexBetween = { display: 'flex', alignItems: 'center', justifyContent: 'space-between' };
const flexStartBetween = { display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between' };

function MetaItem({ label, children }) {
  return (
    <div style={{ ...flex, alignItems: 'center', gap: '12px' }}>
      <div style={{ ...flexCenter, height: '44px', width: '44px', borderRadius: '50%', background: '#FEF2F2' }}>
        <div style={{ width: '8px', height: '8px', borderRadius: '50%', background: '#EF4444' }} />
      </div>
      <div style={flexCol}>
        <div style={{ fontSize: '10px', fontWeight: 700, letterSpacing: '0.05em', color: '#9CA3AF' }}>{label}</div>
        <div style={{ fontSize: '14px', fontWeight: 700, color: '#1E293B' }}>{children}</div>
      </div>
    </div>
  );
}

function StatBox({ label, value, valueColor }) {
  return (
    <div style={{ flex: 1, borderRadius: '12px', border: '1px solid #E5E7EB', padding: '10px 14px', background: '#FFFFFF' }}>
      <div style={{ fontSize: '9px', fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.05em', color: '#9CA3AF' }}>{label}</div>
      <div style={{ marginTop: '2px', fontSize: '16px', fontWeight: 900, color: valueColor || '#1E293B' }}>{inr(value)}</div>
    </div>
  );
}

export default function VendorLedgerReportTemplate({ data, logoSrc }) {
  const { outletName, date, weekday, generatedOn, generatedBy, rows, totals } = data;
  const vendorCount = rows.length;

  const thBase = {
    padding: '10px 14px',
    fontSize: '10px',
    fontWeight: 700,
    textTransform: 'uppercase',
    letterSpacing: '0.05em',
    color: '#6B7280',
  };

  const tdBase = {
    padding: '10px 14px',
    fontSize: '13px',
  };

  return (
    <div
      id="vendor-ledger-report"
      style={{
        width: '900px',
        margin: '0 auto',
        padding: '32px',
        boxSizing: 'border-box',
        fontFamily: "'Inter', 'Helvetica Neue', Arial, sans-serif",
        background: '#FFFFFF',
        color: '#1E293B',
      }}
    >
      {/* ── Header ─────────────────────────────────────────────────── */}
      <div data-bp style={flexStartBetween}>
        <div style={{ ...flex, alignItems: 'center', gap: '12px' }}>
          <div style={{ ...flexCenter, height: '56px', width: '56px', borderRadius: '12px', background: '#E63946' }}>
            <img src={logoSrc} alt="Softshape" style={{ height: '32px', width: '32px', objectFit: 'contain' }} />
          </div>
          <div style={flexCol}>
            <div style={{ fontSize: '20px', fontWeight: 900, color: '#0F172A' }}>Softshape</div>
            <div style={{ fontSize: '9px', fontWeight: 700, letterSpacing: '0.15em', color: '#9CA3AF' }}>
              THE AI OPERATING SYSTEM FOR RESTAURANTS
            </div>
          </div>
        </div>
        <div style={{ textAlign: 'right' }}>
          <h1 style={{ fontSize: '30px', fontWeight: 900, margin: 0 }}>
            <span style={{ color: '#0F172A' }}>VENDOR </span>
            <span style={{ color: '#E63946' }}>BALANCES</span>
          </h1>
        </div>
      </div>
      <div style={{ marginTop: '16px', height: '3px', width: '100%', background: '#E63946' }} />

      {/* ── Meta row ───────────────────────────────────────────────── */}
      <div data-bp style={{ marginTop: '20px', ...flexStartBetween }}>
        <div style={{ ...flex, gap: '32px' }}>
          <MetaItem label="OUTLET">{outletName}</MetaItem>
          <MetaItem label="AS OF DATE">
            {date}
            {weekday && <div style={{ fontSize: '12px', fontWeight: 500, color: '#9CA3AF' }}>{weekday}</div>}
          </MetaItem>
          <MetaItem label="VENDORS">{vendorCount} Vendor{vendorCount !== 1 ? 's' : ''}</MetaItem>
        </div>
        <div style={{ textAlign: 'right', fontSize: '11px', lineHeight: '20px', color: '#6B7280' }}>
          <div><span style={{ fontWeight: 700, color: '#9CA3AF' }}>GENERATED ON: </span>{generatedOn}</div>
          <div><span style={{ fontWeight: 700, color: '#9CA3AF' }}>GENERATED BY: </span>{generatedBy}</div>
        </div>
      </div>

      {/* ── Summary stats ──────────────────────────────────────────── */}
      <div data-bp style={{ marginTop: '20px', ...flex, gap: '10px' }}>
        <StatBox label="Total Opening" value={totals.opening} />
        <StatBox label="Total Purchases" value={totals.purchases} valueColor="#2563EB" />
        <StatBox label="Total Payments" value={totals.payments} valueColor="#16A34A" />
        <StatBox label="Total Outstanding" value={totals.closing} valueColor="#E63946" />
      </div>

      {/* ── Vendor Balances Table ──────────────────────────────────── */}
      <div style={{ marginTop: '20px', borderRadius: '12px', overflow: 'hidden', border: '1px solid #E5E7EB' }}>
        <div data-bp style={{ ...flex, alignItems: 'center', gap: '8px', padding: '10px 16px', background: '#0F172A' }}>
          <span style={{ fontSize: '12px', fontWeight: 700, letterSpacing: '0.05em', color: '#FFFFFF' }}>VENDOR-WISE BALANCES</span>
          <span style={{ marginLeft: 'auto', fontSize: '10px', fontWeight: 600, color: '#9CA3AF' }}>
            Opening + Purchases − Payments = Closing
          </span>
        </div>
        <table style={{ width: '100%', textAlign: 'left', fontSize: '13px', borderCollapse: 'collapse' }}>
          <thead>
            <tr style={{ background: '#F9FAFB' }}>
              <th style={{ ...thBase, textAlign: 'center', width: '40px' }}>#</th>
              <th style={{ ...thBase, textAlign: 'left' }}>Vendor</th>
              <th style={{ ...thBase, textAlign: 'right', width: '120px' }}>Opening (₹)</th>
              <th style={{ ...thBase, textAlign: 'right', width: '120px' }}>Purchases (₹)</th>
              <th style={{ ...thBase, textAlign: 'right', width: '120px' }}>Payments (₹)</th>
              <th style={{ ...thBase, textAlign: 'right', width: '130px' }}>Closing (₹)</th>
            </tr>
          </thead>
          <tbody>
            {rows.map((r, idx) => {
              const closing = round2(r.closingBalance);
              return (
                <tr data-bp key={r.vendorId || idx} style={{ background: idx % 2 === 0 ? '#FFFFFF' : '#F9FAFB', borderBottom: '1px solid #F3F4F6' }}>
                  <td style={{ ...tdBase, textAlign: 'center', fontWeight: 600, color: '#6B7280' }}>{idx + 1}</td>
                  <td style={{ ...tdBase, fontWeight: 700, color: '#1E293B' }}>
                    {r.name}
                    {r.isActive === false && (
                      <span style={{ marginLeft: '8px', fontSize: '9px', fontWeight: 800, textTransform: 'uppercase', padding: '2px 6px', borderRadius: '4px', background: '#F3F4F6', color: '#9CA3AF' }}>Retired</span>
                    )}
                  </td>
                  <td style={{ ...tdBase, textAlign: 'right', fontWeight: 600, color: '#334155' }}>{inrPlain(round2(r.openingBalance))}</td>
                  <td style={{ ...tdBase, textAlign: 'right', fontWeight: 600, color: '#2563EB' }}>{inrPlain(round2(r.purchases))}</td>
                  <td style={{ ...tdBase, textAlign: 'right', fontWeight: 600, color: '#16A34A' }}>{inrPlain(round2(r.payments))}</td>
                  <td style={{ ...tdBase, textAlign: 'right', fontWeight: 900, color: closing > 0 ? '#E63946' : closing < 0 ? '#16A34A' : '#9CA3AF' }}>
                    {inrPlain(Math.abs(closing))}{closing < 0 ? ' (ADV)' : ''}
                  </td>
                </tr>
              );
            })}
          </tbody>
          <tfoot>
            <tr data-bp style={{ background: '#F9FAFB', borderTop: '2px solid #E2E8F0' }}>
              <td colSpan={2} style={{ ...tdBase, fontWeight: 900, textTransform: 'uppercase', fontSize: '11px', color: '#334155' }}>Totals</td>
              <td style={{ ...tdBase, textAlign: 'right', fontWeight: 900, color: '#334155' }}>{inrPlain(round2(totals.opening))}</td>
              <td style={{ ...tdBase, textAlign: 'right', fontWeight: 900, color: '#2563EB' }}>{inrPlain(round2(totals.purchases))}</td>
              <td style={{ ...tdBase, textAlign: 'right', fontWeight: 900, color: '#16A34A' }}>{inrPlain(round2(totals.payments))}</td>
              <td style={{ ...tdBase, textAlign: 'right', fontWeight: 900, color: '#E63946' }}>{inrPlain(round2(totals.closing))}</td>
            </tr>
          </tfoot>
        </table>
      </div>

      {/* ── Footer band ────────────────────────────────────────────── */}
      <div data-bp style={{ marginTop: '24px', ...flexBetween, borderRadius: '12px', padding: '20px', background: '#0F172A' }}>
        <div style={flexCol}>
          <div style={{ fontSize: '10px', fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.05em', color: '#9CA3AF' }}>Total Outstanding Payable</div>
          <div style={{ fontSize: '30px', fontWeight: 900, color: '#4ADE80' }}>{inr(totals.closing)}</div>
          <div style={{ marginTop: '4px', fontSize: '10px', color: '#9CA3AF' }}>{vendorCount} vendor{vendorCount !== 1 ? 's' : ''} · as of {date}</div>
        </div>
        <div style={{ ...flex, gap: '32px', textAlign: 'center', fontSize: '10px', color: '#D1D5DB' }}>
          <div style={flexCol}>
            <div style={{ marginBottom: '16px', width: '96px', borderBottom: '1px solid #6B7280' }} />
            PREPARED BY<br /><span style={{ color: '#6B7280' }}>(Signature)</span>
          </div>
          <div style={flexCol}>
            <div style={{ marginBottom: '16px', width: '96px', borderBottom: '1px solid #6B7280' }} />
            VERIFIED BY<br /><span style={{ color: '#6B7280' }}>(Signature)</span>
          </div>
        </div>
      </div>

      <div style={{ marginTop: '12px', textAlign: 'center', fontSize: '10px', color: '#9CA3AF' }}>
        Softshape AI - software that shapes your business
      </div>
    </div>
  );
}
