const adminGettingStarted = {
  id: 'admin-getting-started',
  name: 'Admin Getting Started',
  description: 'Complete overview of the Admin Panel and how your restaurant operates',
  version: 1,
  portal: 'admin',
  category: 'Getting Started',
  roles: ['admin', 'owner', 'manager'],
  requiredModules: [],
  startRoute: '/admin/dashboard',
  steps: [
    {
      target: '[data-tour="admin-header"]',
      title: 'Welcome to the Admin Panel',
      body: 'This is your restaurant\'s control center. Everything you configure here — menu, tables, staff, printers, pricing — flows to your Cashier and Captain panels through cloud sync.',
      hint: 'The flow is: Admin Configuration → Cloud Sync → Cashier & Captain',
      placement: 'bottom',
    },
    {
      target: '[data-tour="admin-sidebar"]',
      title: 'Navigation Sidebar',
      body: 'The sidebar is your map to every section of the Admin Panel. Each item opens a different module: Dashboard, Tables, Menu, Orders, Transactions, Reports, Inventory, Purchases, Printers, Staff, Settings, and more.',
      hint: 'You can drag sidebar items to reorder them. Your custom order is saved automatically.',
      placement: 'right',
    },
    {
      target: '[data-tour="admin-dashboard"]',
      title: 'Today\'s Business Overview',
      body: 'The dashboard shows today\'s sales, revenue, order count, discounts, and net sales at a glance. The activity log shows real-time events like new orders, billing requests, and payments as they happen.',
      hint: 'Dashboard data updates in real-time via WebSocket. You don\'t need to refresh.',
      placement: 'bottom',
    },
    {
      target: '[data-tour="admin-dashboard-stats"]',
      title: 'Sales & Revenue Statistics',
      body: 'These cards show today\'s total revenue, total sales, net sales, total discount, and order count. Use the date selector to view statistics for any specific day.',
      hint: 'If you have multiple outlets, use the outlet switcher in the header to compare performance.',
      placement: 'bottom',
    },
    {
      target: '[data-tour="admin-dashboard-activity"]',
      title: 'Activity Log',
      body: 'The activity log shows a live feed of what\'s happening in your restaurant: new orders, billing requests, table status changes, and payment completions. This gives you real-time visibility into operations.',
      placement: 'bottom',
    },
    {
      target: '[data-tour="admin-sidebar"]',
      title: 'Explore Each Module',
      body: 'Each sidebar item has its own dedicated tour. Click the "?" tour button in any module to learn how it works in detail. You can also open the Tour Guide Center from the help button at the bottom-left to see all available tours.',
      hint: 'Start with Menu Management — it\'s the first thing you need to configure.',
      placement: 'right',
    },
    {
      target: '[data-tour="admin-sidebar"]',
      title: 'The Complete Restaurant Flow',
      body: 'Here\'s how Softshape works end-to-end: 1) Admin configures menu, tables, printers, staff, and pricing. 2) Changes sync to Cashier and Captain via cloud. 3) Captains take orders at tables. 4) Cashiers generate bills and settle payments. 5) Admin monitors everything via reports and dashboard.',
      hint: 'Use the Tour Guide Center (bottom-left help button) to explore each module in detail.',
      placement: 'right',
    },
  ],
};

const adminDashboard = {
  id: 'admin-dashboard-tour',
  name: 'Admin Dashboard Tour',
  description: 'Understand the dashboard, statistics, and real-time monitoring',
  version: 1,
  portal: 'admin',
  category: 'Admin',
  roles: ['admin', 'owner', 'manager'],
  requiredModules: [],
  startRoute: '/admin/dashboard',
  steps: [
    {
      target: '[data-tour="admin-dashboard-stats"]',
      title: 'Business Statistics',
      body: 'These cards display today\'s key metrics: Total Revenue (including tax), Total Sales (subtotal), Net Sales (after discounts), Total Discount given, and Order Count. This is your daily business snapshot.',
      hint: 'Use the date selector to view any day\'s statistics.',
      placement: 'bottom',
    },
    {
      target: '[data-tour="admin-dashboard-activity"]',
      title: 'Real-Time Activity Log',
      body: 'This feed shows live events from your restaurant: new orders being created, billing requests from captains, payment completions, and table status changes. Events appear here within seconds of happening.',
      hint: 'The activity log is powered by WebSocket — no refresh needed.',
      placement: 'bottom',
    },
    {
      target: '[data-tour="admin-header"]',
      title: 'Date & Outlet Controls',
      body: 'Use the date selector in the header to view statistics for any day. If you manage multiple outlets, use the outlet switcher to view data for a specific outlet or compare all outlets together.',
      placement: 'bottom',
    },
    {
      target: '[data-tour="admin-dashboard"]',
      title: 'Important Alerts',
      body: 'Watch for kitchen low-stock alerts that appear as toast notifications in the top-right corner. These warn you when ingredients are running low and need reordering. The trial banner at the top shows your subscription status.',
      hint: 'Address low-stock alerts promptly to avoid running out of key ingredients.',
      placement: 'bottom',
    },
    {
      target: '[data-tour="admin-dashboard"]',
      title: 'Key Actions',
      body: 'From the dashboard, you can monitor your restaurant\'s real-time performance, check today\'s revenue, identify busy periods, and spot issues like pending bills or low stock. Use the sidebar to dive deeper into any area.',
      placement: 'bottom',
    },
  ],
};

const adminMenu = {
  id: 'admin-menu-tour',
  name: 'Menu Management Tour',
  description: 'Create and manage the items your restaurant sells',
  version: 1,
  portal: 'admin',
  category: 'Admin',
  roles: ['admin', 'owner', 'manager'],
  requiredModules: [],
  startRoute: '/admin/menu',
  steps: [
    {
      target: '[data-tour="admin-menu"]',
      title: 'Menu Management',
      body: 'This is where you create and maintain your restaurant\'s menu. Everything you configure here — categories, items, prices, availability — is synchronized to the Cashier and Captain panels so they can take orders.',
      hint: 'The flow is: Create Category → Create Item → Set Price → Make Available → Sync → Cashier & Captain receive it.',
      placement: 'bottom',
    },
    {
      target: '[data-tour="admin-menu-categories"]',
      title: 'Categories',
      body: 'Categories organize your menu (e.g., Starters, Main Course, Beverages, Desserts). Cashiers and Captains browse by category to find items quickly. Create categories that match your kitchen\'s workflow.',
      hint: 'You can reorder categories by dragging. The order here is the order shown in the POS.',
      placement: 'right',
    },
    {
      target: '[data-tour="admin-menu-add-item"]',
      title: 'Adding a Menu Item',
      body: 'Click "Add Item" to create a new dish. You\'ll enter the item name, select a category, set the price, choose dietary type (veg/non-veg), and optionally add a description, image, and GST rate.',
      hint: 'You can also use AI Dish Creation (the sparkle button) to generate item details from a photo or description.',
      placement: 'bottom',
    },
    {
      target: '[data-tour="admin-menu-items"]',
      title: 'Menu Items List',
      body: 'This list shows all your menu items. Each item shows its name, category, price, dietary type, and availability status. You can edit any item by clicking on it, or toggle availability to temporarily hide out-of-stock items.',
      hint: 'Unavailable items are hidden from Cashier and Captain but remain in your menu for future reactivation.',
      placement: 'top',
    },
    {
      target: '[data-tour="admin-menu-items"]',
      title: 'Editing an Item',
      body: 'Click any item to edit its name, price, category, dietary type, GST rate, description, and image. Changes are saved to the edge server first (works offline), then synced to the cloud. Cashier and Captain receive the updated menu automatically.',
      hint: 'Price changes take effect immediately on new orders. Existing orders keep the original price.',
      placement: 'top',
    },
    {
      target: '[data-tour="admin-menu-items"]',
      title: 'Item Pricing',
      body: 'Each item has a base price. If you have multiple outlets with different pricing, you can set outlet-specific prices using Price Profiles (found in the sidebar). GST rates can be set per item or inherited from the category default.',
      hint: 'For bar items, you can configure different prices for different quantities (e.g., 30ml, 60ml, full bottle).',
      placement: 'top',
    },
    {
      target: '[data-tour="admin-menu-items"]',
      title: 'Item Availability',
      body: 'Toggle an item\'s availability to control whether Cashier and Captain can order it. Use this when items run out of stock or are seasonal. Unavailable items stay in your menu but are greyed out in the POS.',
      hint: 'Availability changes sync instantly to all connected devices.',
      placement: 'top',
    },
    {
      target: '[data-tour="admin-menu-items"]',
      title: 'Bulk Import & AI Parsing',
      body: 'You can bulk-import menu items from a CSV/Excel file, or use AI menu parsing to extract items from a photo of your menu card. This saves time when setting up a large menu for the first time.',
      hint: 'Look for the "Import" and "AI Parse" buttons at the top of the menu page.',
      placement: 'top',
    },
    {
      target: '[data-tour="admin-menu"]',
      title: 'How Menu Reaches Cashier & Captain',
      body: 'When you add or modify a menu item, the change is saved to the local edge server immediately (works offline). The sync engine then pushes the change to the cloud. Cashier and Captain devices pull the updated menu on their next sync cycle or receive it via WebSocket if online.',
      hint: 'Menu changes typically reach operational panels within seconds when online.',
      placement: 'bottom',
    },
  ],
};

const adminTables = {
  id: 'admin-tables-tour',
  name: 'Tables & Floor Tour',
  description: 'Configure your restaurant\'s table layout and sections',
  version: 1,
  portal: 'admin',
  category: 'Admin',
  roles: ['admin', 'owner', 'manager'],
  requiredModules: [],
  startRoute: '/admin/tables',
  steps: [
    {
      target: '[data-tour="admin-tables"]',
      title: 'Tables & Floor Management',
      body: 'This is where you configure your restaurant\'s physical layout. Tables created here are used by Cashier and Captain to manage orders. Each table tracks its status (Free, Occupied, Preparing, Ready, Waiting Bill) in real-time.',
      placement: 'bottom',
    },
    {
      target: '[data-tour="admin-tables-sections"]',
      title: 'Sections',
      body: 'Sections group tables by location (e.g., Ground Floor, First Floor, Outdoor, Bar). Create sections that match your restaurant\'s physical layout. Captains and Cashiers filter by section to quickly find their tables.',
      hint: 'Sections help staff navigate large restaurants more efficiently.',
      placement: 'right',
    },
    {
      target: '[data-tour="admin-tables-grid"]',
      title: 'Creating Tables',
      body: 'Add tables by specifying a table number/name and assigning it to a section. Each table becomes a unit in the POS where orders are placed, KOTs are sent, and bills are generated.',
      hint: 'Table numbers should match your physical table numbering for easy identification.',
      placement: 'top',
    },
    {
      target: '[data-tour="admin-tables-grid"]',
      title: 'Table Status',
      body: 'Each table has a status: Free (ready for new guests), Occupied (has an active order), Preparing (KOT sent, food being prepared), Ready (food ready to serve), Waiting Bill (captain requested bill). Status changes happen automatically as orders flow through the system.',
      hint: 'Table status updates in real-time across all panels via WebSocket.',
      placement: 'top',
    },
    {
      target: '[data-tour="admin-tables-qr"]',
      title: 'QR Codes',
      body: 'Each table can have a QR code that customers scan to view a digital menu. QR codes can be printed and placed on tables. Visit the QR Codes section in the sidebar to generate and print table QR codes.',
      hint: 'QR codes link to a digital menu where customers can browse items and place orders.',
      placement: 'top',
    },
    {
      target: '[data-tour="admin-tables"]',
      title: 'How Tables Are Used',
      body: 'Cashier: selects a table → takes order → sends KOT → generates bill → settles payment → table becomes Free. Captain: selects a table → browses menu → adds items → sends KOT → Cashier handles billing. Admin: monitors table status in real-time from the dashboard.',
      placement: 'bottom',
    },
  ],
};

const adminOrders = {
  id: 'admin-orders-tour',
  name: 'Orders Tour',
  description: 'Understand the complete order journey from creation to settlement',
  version: 1,
  portal: 'admin',
  category: 'Admin',
  roles: ['admin', 'owner', 'manager'],
  requiredModules: [],
  startRoute: '/admin/orders',
  steps: [
    {
      target: '[data-tour="admin-orders"]',
      title: 'Order Management',
      body: 'This page shows all orders in your restaurant. Orders are created by Captains at the table or by Cashiers from the POS. Each order goes through a lifecycle: Created → KOT Sent → Preparing → Ready → Billed → Settled.',
      placement: 'bottom',
    },
    {
      target: '[data-tour="admin-orders-list"]',
      title: 'Live Orders',
      body: 'The orders list shows active orders with their current status, table number, items, and total amount. You can filter by status to see only pending, preparing, ready, or billed orders.',
      hint: 'Orders update in real-time. You don\'t need to refresh the page.',
      placement: 'right',
    },
    {
      target: '[data-tour="admin-orders-list"]',
      title: 'Order Status & KOT',
      body: 'When a Captain or Cashier sends an order, a KOT (Kitchen Order Ticket) is generated and printed in the kitchen. The kitchen prepares the items, marks them as ready, and the order status updates. This flow ensures kitchen and service staff stay in sync.',
      hint: 'KOT contains item names, quantities, and special instructions for the kitchen.',
      placement: 'right',
    },
    {
      target: '[data-tour="admin-orders-list"]',
      title: 'Kitchen / Bar Flow',
      body: 'Food items go to the kitchen printer, bar items go to the bar printer. Each KOT is routed based on item configuration. The kitchen sees the KOT, prepares the items, and the order status changes to "Ready" when food is done.',
      placement: 'right',
    },
    {
      target: '[data-tour="admin-orders"]',
      title: 'The Complete Order Journey',
      body: 'Captain selects table → adds items to cart → sends KOT → kitchen receives KOT → kitchen prepares → order status becomes Ready → Cashier generates bill → customer pays → Cashier settles → table becomes Free. Admin monitors the entire flow from this page.',
      hint: 'You can view order details, modify items, and track timing for each stage.',
      placement: 'bottom',
    },
  ],
};

const adminTransactions = {
  id: 'admin-transactions-tour',
  name: 'Transactions & Billing Tour',
  description: 'Understand billing, payments, and transaction history',
  version: 1,
  portal: 'admin',
  category: 'Admin',
  roles: ['admin', 'owner', 'manager'],
  requiredModules: [],
  startRoute: '/admin/transactions',
  steps: [
    {
      target: '[data-tour="admin-transactions"]',
      title: 'Transaction History',
      body: 'This page shows all transactions (bills) processed by your restaurant. Each transaction includes the bill number, table, items, subtotal, taxes, discounts, total amount, payment method, and settlement status.',
      placement: 'bottom',
    },
    {
      target: '[data-tour="admin-transactions-list"]',
      title: 'Viewing Bills',
      body: 'Click any transaction to view the full bill details: itemized list with quantities and prices, applied discounts, tax breakdown (CGST/SGST), and the final amount. You can see exactly what the customer was charged.',
      hint: 'Bill details match what was printed on the customer\'s receipt.',
      placement: 'right',
    },
    {
      target: '[data-tour="admin-transactions-list"]',
      title: 'Payment Information',
      body: 'Each transaction shows the payment method used (Cash, Card, UPI, or Split), the amount paid, tip if any, and settlement timestamp. For split payments, you can see the breakdown across multiple payment methods.',
      placement: 'right',
    },
    {
      target: '[data-tour="admin-transactions-list"]',
      title: 'Discounts & Taxes',
      body: 'Transactions show any discounts applied (percentage or flat amount) and the tax breakdown. This helps you track how much discount you\'re giving and verify tax collection for GST filing.',
      placement: 'right',
    },
    {
      target: '[data-tour="admin-transactions-list"]',
      title: 'Bill Editing & Reprinting',
      body: 'Admins can edit a bill after settlement if corrections are needed (e.g., wrong item, wrong price). You can also reprint bills for customer requests. Bill edits are logged in the audit trail for accountability.',
      hint: 'Bill edits should be done carefully — they affect your financial reports.',
      placement: 'right',
    },
    {
      target: '[data-tour="admin-transactions"]',
      title: 'Filters & Date-Based History',
      body: 'Use the date filter to view transactions for any period. Filter by payment method, settlement status, or table. This is useful for end-of-day reconciliation, investigating discrepancies, and generating reports.',
      hint: 'Admin can view all transactions. Cashier normally handles day-to-day billing.',
      placement: 'bottom',
    },
  ],
};

const adminInventory = {
  id: 'admin-inventory-tour',
  name: 'Inventory Tour',
  description: 'Manage kitchen and bar inventory, stock, and consumption',
  version: 1,
  portal: 'admin',
  category: 'Admin',
  roles: ['admin', 'owner', 'manager'],
  requiredModules: [],
  startRoute: '/admin/kitchen-inventory',
  steps: [
    {
      target: '[data-tour="admin-inventory"]',
      title: 'Inventory Management',
      body: 'Track your kitchen and bar inventory here. Know exactly how much stock you have, what you need to purchase, and how menu sales are consuming your ingredients.',
      hint: 'The flow is: Purchase → Inventory → Menu Sale → Stock Consumption',
      placement: 'bottom',
    },
    {
      target: '[data-tour="admin-inventory-items"]',
      title: 'Inventory Items',
      body: 'Each inventory item has a name, unit (kg, liter, piece), opening stock, current stock, and reorder level. Items can be kitchen ingredients (flour, oil, vegetables) or bar stock (liquor bottles, mixers).',
      hint: 'Set reorder levels so you get alerts when stock is running low.',
      placement: 'right',
    },
    {
      target: '[data-tour="admin-inventory-items"]',
      title: 'Opening Stock',
      body: 'When you first set up an inventory item, enter its opening stock — the quantity you currently have. This becomes the baseline for tracking all future additions and consumption.',
      placement: 'right',
    },
    {
      target: '[data-tour="admin-inventory-items"]',
      title: 'Stock Additions & Purchases',
      body: 'When you purchase new stock, add it here or through the Purchases module. Stock additions increase the current stock level. Each addition is logged with the date, quantity, and source.',
      hint: 'Purchases made in the Purchases module automatically update inventory levels.',
      placement: 'right',
    },
    {
      target: '[data-tour="admin-inventory-items"]',
      title: 'Stock Consumption',
      body: 'When menu items are sold, the associated ingredients are automatically deducted from inventory (if recipe mapping is configured). You can also manually adjust stock for wastage, spoilage, or physical count corrections.',
      hint: 'Recipe mapping connects menu items to their ingredients for automatic consumption tracking.',
      placement: 'right',
    },
    {
      target: '[data-tour="admin-inventory-items"]',
      title: 'Current Stock & Movement',
      body: 'The current stock column shows your real-time inventory level. The stock movement history shows every addition, consumption, and adjustment with timestamps. Use this to audit your inventory and identify discrepancies.',
      placement: 'right',
    },
    {
      target: '[data-tour="admin-inventory"]',
      title: 'Inventory Reports',
      body: 'Inventory reports show stock valuation, consumption patterns, and low-stock alerts. Use these reports to optimize purchasing, reduce wastage, and ensure you never run out of key ingredients.',
      hint: 'Kitchen low-stock alerts appear on the Admin Dashboard as toast notifications.',
      placement: 'bottom',
    },
  ],
};

const adminPurchases = {
  id: 'admin-purchases-tour',
  name: 'Purchases Tour',
  description: 'Manage vendors, purchase orders, and inventory impact',
  version: 1,
  portal: 'admin',
  category: 'Admin',
  roles: ['admin', 'owner', 'manager'],
  requiredModules: [],
  startRoute: '/admin/purchases',
  steps: [
    {
      target: '[data-tour="admin-purchases"]',
      title: 'Purchase Management',
      body: 'Track all your restaurant purchases here. Every purchase you record updates your inventory levels and financial records. This gives you a complete picture of what you\'re spending and who you owe.',
      hint: 'Purchases affect both inventory (stock increases) and finance (vendor liabilities).',
      placement: 'bottom',
    },
    {
      target: '[data-tour="admin-purchases-vendors"]',
      title: 'Vendors',
      body: 'Add and manage your suppliers/vendors. Each vendor has a name, contact info, and an outstanding balance. Track how much you owe each vendor and when payments are due.',
      hint: 'Vendor balances feed into your balance sheet as accounts payable.',
      placement: 'right',
    },
    {
      target: '[data-tour="admin-purchases-list"]',
      title: 'Purchase Entries',
      body: 'Record each purchase with the vendor, items purchased, quantities, rates, and total amount. Each purchase entry automatically increases the corresponding inventory items\' stock levels.',
      hint: 'You can also record daily purchases for small, routine buys like vegetables.',
      placement: 'right',
    },
    {
      target: '[data-tour="admin-purchases-list"]',
      title: 'Payment Status',
      body: 'Each purchase has a payment status: Paid, Partially Paid, or Unpaid. Track which vendors you need to pay and how much. Mark purchases as paid when you settle the vendor\'s bill.',
      placement: 'right',
    },
    {
      target: '[data-tour="admin-purchases-list"]',
      title: 'Purchase History',
      body: 'View all past purchases filtered by date, vendor, or payment status. This helps you analyze spending patterns, negotiate better rates with vendors, and prepare for tax filing.',
      hint: 'Purchase history feeds into COGS (Cost of Goods Sold) reports.',
      placement: 'right',
    },
    {
      target: '[data-tour="admin-purchases"]',
      title: 'Inventory & Financial Impact',
      body: 'Every purchase does two things: 1) Increases inventory stock for the purchased items. 2) Creates a vendor liability in your financial records. When you pay the vendor, the liability is settled. This keeps your inventory and books always in sync.',
      placement: 'bottom',
    },
  ],
};

const adminExpenditures = {
  id: 'admin-expenditures-tour',
  name: 'Expenditures Tour',
  description: 'Track and categorize business expenses',
  version: 1,
  portal: 'admin',
  category: 'Admin',
  roles: ['admin', 'owner', 'manager'],
  requiredModules: [],
  startRoute: '/admin/vouchers',
  steps: [
    {
      target: '[data-tour="admin-expenditures"]',
      title: 'Expenditure Tracking',
      body: 'Record all business expenses here — rent, electricity, salaries, maintenance, marketing, and any other spending. Categorized expenditures feed into your financial reports and help you understand your true profitability.',
      placement: 'bottom',
    },
    {
      target: '[data-tour="admin-expenditures-add"]',
      title: 'Adding an Expenditure',
      body: 'Click "Add Expenditure" to record a new expense. Enter the amount, category, payment method, date, and an optional description. Each expenditure is logged with a timestamp for audit purposes.',
      hint: 'Be consistent with categories — this makes your reports more useful.',
      placement: 'bottom',
    },
    {
      target: '[data-tour="admin-expenditures-categories"]',
      title: 'Categories',
      body: 'Categorize expenditures (e.g., Rent, Utilities, Salaries, Maintenance, Marketing, Supplies). Categories help you analyze where your money is going and identify areas to optimize.',
      placement: 'right',
    },
    {
      target: '[data-tour="admin-expenditures-list"]',
      title: 'Payment Methods & Vendor Liabilities',
      body: 'Each expenditure records the payment method (Cash, Bank, UPI). Unpaid expenditures create vendor liabilities that appear in your balance sheet. Mark them as settled when you make the payment.',
      placement: 'right',
    },
    {
      target: '[data-tour="admin-expenditures-list"]',
      title: 'Expenditure History',
      body: 'View all past expenditures filtered by date, category, or payment status. This history is essential for tax filing, budgeting, and financial planning. Expenditures are included in your daily balance sheet and profit & loss calculations.',
      hint: 'Expenditures directly affect your net profit calculation in financial reports.',
      placement: 'right',
    },
  ],
};

const adminPrinters = {
  id: 'admin-printers-tour',
  name: 'Printer Configuration Tour',
  description: 'Set up kitchen, bar, and bill printers for KOT and bill printing',
  version: 1,
  portal: 'admin',
  category: 'Admin',
  roles: ['admin', 'owner', 'manager'],
  requiredModules: [],
  startRoute: '/admin/printers',
  steps: [
    {
      target: '[data-tour="admin-printers"]',
      title: 'Printer Configuration',
      body: 'Configure your printers here. Softshape supports three types of printers: Kitchen Printer (for KOTs), Bar Printer (for bar orders), and Bill Printer (for customer bills). Proper printer setup ensures smooth kitchen and bar operations.',
      hint: 'Without printer setup, KOTs and bills can only be viewed on screen.',
      placement: 'bottom',
    },
    {
      target: '[data-tour="admin-printers-add"]',
      title: 'Adding a Printer',
      body: 'Click "Add Printer" to configure a new printer. You\'ll specify the printer name, connection type (USB, network, Bluetooth), and printer type (Kitchen, Bar, Bill). The system uses QZ Tray for direct printing from the browser.',
      hint: 'QZ Tray must be installed on the device connected to the printer.',
      placement: 'bottom',
    },
    {
      target: '[data-tour="admin-printers-list"]',
      title: 'Kitchen Printer',
      body: 'The kitchen printer receives KOTs (Kitchen Order Tickets) whenever a Captain or Cashier sends an order. Each KOT lists the items, quantities, and special instructions. The kitchen printer ensures kitchen staff see orders immediately.',
      hint: 'Food items are routed to the kitchen printer based on item configuration.',
      placement: 'right',
    },
    {
      target: '[data-tour="admin-printers-list"]',
      title: 'Bar Printer',
      body: 'The bar printer receives bar orders — drinks, cocktails, and beverages. Bar items are automatically routed to the bar printer, separate from food items going to the kitchen. This prevents congestion at the kitchen printer.',
      hint: 'Bar printer is only needed if your restaurant serves alcohol or beverages.',
      placement: 'right',
    },
    {
      target: '[data-tour="admin-printers-list"]',
      title: 'Bill Printer',
      body: 'The bill printer generates customer receipts when the Cashier settles a bill. The bill includes itemized list, prices, taxes, discounts, total amount, and payment details. A printed bill is the customer\'s proof of purchase.',
      placement: 'right',
    },
    {
      target: '[data-tour="admin-printers-list"]',
      title: 'Printer Mapping',
      body: 'Map which items go to which printer. By default, food items go to the kitchen printer and bar items go to the bar printer. You can customize this mapping per item if needed (e.g., send desserts to a separate dessert station printer).',
      hint: 'Printer mapping is configured per menu item in Menu Management.',
      placement: 'right',
    },
    {
      target: '[data-tour="admin-printers"]',
      title: 'How KOT Printing Works',
      body: 'When a Captain or Cashier sends an order: 1) A KOT is generated with a unique KOT number. 2) The KOT is printed to the appropriate kitchen/bar printer. 3) The kitchen/bar prepares the items. 4) The order status updates in real-time. Admin configuration here determines where each KOT goes.',
      placement: 'bottom',
    },
  ],
};

const adminStaff = {
  id: 'admin-staff-tour',
  name: 'Staff Management Tour',
  description: 'Manage captains, cashiers, roles, and permissions',
  version: 1,
  portal: 'admin',
  category: 'Admin',
  roles: ['admin', 'owner'],
  requiredModules: [],
  startRoute: '/admin/staff',
  steps: [
    {
      target: '[data-tour="admin-staff"]',
      title: 'Staff Management',
      body: 'Manage your restaurant staff here. Add captains (waiters who take orders) and cashiers (who handle billing). Each staff member gets credentials and a PIN for quick login on shared devices.',
      placement: 'bottom',
    },
    {
      target: '[data-tour="admin-staff-add"]',
      title: 'Adding Staff',
      body: 'Click "Add Staff" to create a new team member. Enter their name, role (Captain or Cashier), phone number, and a PIN. The PIN is used for fast login on the Cashier and Captain apps without entering full credentials each time.',
      hint: 'PINs should be unique per staff member for accountability.',
      placement: 'bottom',
    },
    {
      target: '[data-tour="admin-staff-list"]',
      title: 'Roles & Permissions',
      body: 'Each role has different access: Admin/Owner — full access to all panels and settings. Manager — limited admin access to assigned modules only. Cashier — access to POS, tables, billing, and transactions. Captain — access to floor, tables, and order creation.',
      hint: 'Manager tab access is configured in Settings → Manager tab toggles.',
      placement: 'right',
    },
    {
      target: '[data-tour="admin-staff-list"]',
      title: 'PIN / Access Control',
      body: 'Each staff member logs in with their phone number and PIN. PINs can be changed anytime. When a staff member leaves, simply deactivate their account — they\'ll no longer be able to log in.',
      placement: 'right',
    },
    {
      target: '[data-tour="admin-staff-list"]',
      title: 'Shifts & Attendance',
      body: 'Track staff attendance and working hours in the Attendance section. If payroll is enabled, you can generate payslips based on attendance records. This helps you manage labor costs and ensure fair compensation.',
      hint: 'Attendance and Payroll are available in the HR section of the sidebar.',
      placement: 'right',
    },
    {
      target: '[data-tour="admin-staff"]',
      title: 'How Each Role Uses Softshape',
      body: 'Admin/Owner: Configures everything, monitors reports, manages finances. Cashier: Takes orders at the counter, generates bills, settles payments, handles transactions. Captain: Takes orders at tables, sends KOTs to kitchen, manages table status. Manager: Monitors assigned modules based on admin-granted access.',
      placement: 'bottom',
    },
  ],
};

const adminPricing = {
  id: 'admin-pricing-tour',
  name: 'Pricing & Configuration Tour',
  description: 'Understand pricing profiles, taxes, and restaurant configuration',
  version: 1,
  portal: 'admin',
  category: 'Admin',
  roles: ['admin', 'owner', 'manager'],
  requiredModules: [],
  startRoute: '/admin/pricing',
  steps: [
    {
      target: '[data-tour="admin-pricing"]',
      title: 'Pricing Management',
      body: 'Configure how your menu items are priced. You can set different prices for different outlets, create price profiles for special occasions (happy hours, festival menus), and manage tax rates.',
      placement: 'bottom',
    },
    {
      target: '[data-tour="admin-pricing-profiles"]',
      title: 'Price Profiles',
      body: 'Price profiles let you create multiple pricing tiers. For example, a "Happy Hour" profile with discounted drink prices, or a "Festival" profile with special menu pricing. Apply profiles to specific outlets or time periods.',
      hint: 'Price profiles are found in the sidebar under "Price Profiles".',
      placement: 'right',
    },
    {
      target: '[data-tour="admin-pricing"]',
      title: 'Outlet-Specific Pricing',
      body: 'If you have multiple outlets, you can set different prices for the same item at different locations. This is useful when costs vary by location or when positioning outlets differently in the market.',
      placement: 'bottom',
    },
    {
      target: '[data-tour="admin-pricing"]',
      title: 'Taxes & GST',
      body: 'Configure GST rates (CGST + SGST) that are automatically applied to bills. You can set different tax rates for different item categories. Tax configuration is also available in Settings → Tax Configuration.',
      hint: 'GST rates can be set per item in Menu Management or globally in Settings.',
      placement: 'bottom',
    },
    {
      target: '[data-tour="admin-pricing"]',
      title: 'Restaurant Configuration',
      body: 'Visit Settings in the sidebar to configure: restaurant profile, GST details, branding (logo, colors), business hours, receipt format, and app download links. These settings control how your restaurant appears on bills and in the app.',
      hint: 'Settings is only accessible to Admin and Owner roles.',
      placement: 'bottom',
    },
  ],
};

const adminReports = {
  id: 'admin-reports-tour',
  name: 'Reports & Finance Tour',
  description: 'Understand sales reports, GST, balance sheets, COGS, and audit trails',
  version: 1,
  portal: 'admin',
  category: 'Admin',
  roles: ['admin', 'owner', 'manager'],
  requiredModules: [],
  startRoute: '/admin/reports',
  steps: [
    {
      target: '[data-tour="admin-reports"]',
      title: 'Reports & Analytics',
      body: 'This is your financial and operational analytics hub. Generate detailed reports for sales, GST, captain performance, section performance, and more. Reports help you make data-driven decisions about your restaurant.',
      placement: 'bottom',
    },
    {
      target: '[data-tour="admin-reports-sales"]',
      title: 'Sales Reports',
      body: 'View daily, weekly, and monthly sales reports. See revenue, net sales, discounts, and order counts over time. Filter by outlet, date range, or payment method. Export to PDF or Excel for accounting and tax filing.',
      hint: 'Sales reports are essential for tracking business growth and seasonality.',
      placement: 'right',
    },
    {
      target: '[data-tour="admin-reports-gst"]',
      title: 'GST Reports',
      body: 'Generate GST-compliant reports showing tax collected (CGST + SGST) for any period. These reports match the format required for GST filing. Filter by date range and export for your accountant.',
      hint: 'GST reports are based on settled transactions only.',
      placement: 'right',
    },
    {
      target: '[data-tour="admin-reports-captain"]',
      title: 'Captain Reports',
      body: 'Analyze captain performance: number of orders taken, tables served, average order value, and items sold. Use this to identify your best performers and areas for training.',
      placement: 'right',
    },
    {
      target: '[data-tour="admin-reports-section"]',
      title: 'Section Reports',
      body: 'Compare performance across sections (Ground Floor vs. First Floor vs. Outdoor). See which sections generate the most revenue and have the highest table turnover. Optimize staffing and layout based on this data.',
      placement: 'right',
    },
    {
      target: '[data-tour="admin-reports"]',
      title: 'Balance Sheet',
      body: 'The Daily Balance Sheet (in the Finance section) shows your daily financial position: revenue, expenses, purchases, expenditures, assets, and liabilities. Use it for end-of-day reconciliation and to track your restaurant\'s financial health.',
      hint: 'Balance sheet is found in the sidebar under Finance → Daily Balance Sheet.',
      placement: 'bottom',
    },
    {
      target: '[data-tour="admin-reports"]',
      title: 'COGS & Reconciliation',
      body: 'COGS (Cost of Goods Sold) reports show how much your sold items cost to make — helping you calculate actual profit margins. Reconciliation helps match your recorded transactions with bank statements and cash counts to identify discrepancies.',
      hint: 'COGS and Reconciliation are in the Finance section of the sidebar.',
      placement: 'bottom',
    },
    {
      target: '[data-tour="admin-reports"]',
      title: 'Audit Trail & Assets/Liabilities',
      body: 'The Audit Trail logs every financial action (bill edits, settlements, expenditure changes) for accountability. Assets & Liabilities tracks what your restaurant owns and owes. Together, these give you a complete financial picture.',
      hint: 'Audit Trail is especially important for detecting and investigating discrepancies.',
      placement: 'bottom',
    },
    {
      target: '[data-tour="admin-reports"]',
      title: 'Export Functionality',
      body: 'Most reports can be exported as PDF or Excel files. Use this for sharing with your accountant, submitting for tax filing, or keeping offline records. Exports include all applied filters and date ranges.',
      placement: 'bottom',
    },
  ],
};

const adminCloudSync = {
  id: 'admin-cloud-sync-tour',
  name: 'Cloud Sync Tour',
  description: 'Understand how data flows between Admin, Cashier, and Captain',
  version: 1,
  portal: 'admin',
  category: 'Cloud Sync',
  roles: ['admin', 'owner', 'manager'],
  requiredModules: [],
  startRoute: '/admin/dashboard',
  steps: [
    {
      target: '[data-tour="admin-header"]',
      title: 'Cloud Synchronization',
      body: 'Softshape uses an offline-first architecture. All panels work even without internet. When you make changes in Admin, they\'re saved locally first, then synced to the cloud. Cashier and Captain devices receive updates when they\'re online.',
      hint: 'The flow is: Admin makes changes → Local edge server → Cloud → Cashier & Captain receive updates.',
      placement: 'bottom',
    },
    {
      target: '[data-tour="sync-status"]',
      title: 'Sync Status Indicator',
      body: 'The sync status indicator (usually in the header or status bar) shows your current connection state: Online (synced), Offline (working locally), or Syncing (uploading pending actions). Watch this to know if your data is up-to-date.',
      hint: 'A green indicator means you\'re online and synced. A yellow/red indicator means you\'re offline.',
      placement: 'bottom',
    },
    {
      target: '[data-tour="admin-header"]',
      title: 'What Gets Synchronized',
      body: 'Admin changes that sync to the cloud include: menu items (add, edit, price, availability), table configurations, staff accounts, printer settings, pricing profiles, and restaurant settings. Cashier and Captain pull these updates on their next sync cycle.',
      hint: 'Menu and table changes also push via WebSocket for near-instant updates when online.',
      placement: 'bottom',
    },
    {
      target: '[data-tour="admin-header"]',
      title: 'How Cashier Receives Updates',
      body: 'When online, the Cashier panel receives menu and table updates via WebSocket in real-time. When offline, the Cashier stores orders locally in IndexedDB and syncs them to the cloud when connectivity returns. The sync engine replays all pending actions automatically.',
      hint: 'Cashier never stops working — it always accepts orders, online or offline.',
      placement: 'bottom',
    },
    {
      target: '[data-tour="admin-header"]',
      title: 'How Captain Receives Updates',
      body: 'The Captain app connects to the edge server (local SQLite) for menu and table data. When the edge server syncs with the cloud, the Captain receives updated configurations. Orders taken by Captains are queued and synced back to the cloud.',
      hint: 'Captain app is designed for mobile devices and prioritizes offline operation.',
      placement: 'bottom',
    },
    {
      target: '[data-tour="sync-status"]',
      title: 'Pending Sync & Retry',
      body: 'When offline, actions are queued in the sync engine. The pending count shows how many actions are waiting. When internet returns, the engine automatically replays all pending actions. If an action fails (e.g., conflict), it\'s marked for manual resolution.',
      hint: 'Check the sync status regularly if you\'ve been offline for extended periods.',
      placement: 'bottom',
    },
    {
      target: '[data-tour="admin-header"]',
      title: 'Offline Behavior',
      body: 'When the internet goes down: 1) All panels continue working using local data. 2) Orders, KOTs, and settlements are stored locally. 3) Menu and table data remains available from the last sync. 4) No data is lost — everything is queued for sync.',
      placement: 'bottom',
    },
    {
      target: '[data-tour="admin-header"]',
      title: 'When Internet Returns',
      body: 'When connectivity is restored: 1) The sync engine automatically starts replaying queued actions. 2) Conflicts (if any) are flagged for resolution. 3) Cloud data is pulled to update local caches. 4) All panels return to real-time sync via WebSocket. 5) You\'ll see the sync status change from "Offline" to "Syncing" to "Online".',
      hint: 'You don\'t need to do anything — sync happens automatically.',
      placement: 'bottom',
    },
  ],
};

export default [
  adminGettingStarted,
  adminDashboard,
  adminMenu,
  adminTables,
  adminOrders,
  adminTransactions,
  adminInventory,
  adminPurchases,
  adminExpenditures,
  adminPrinters,
  adminStaff,
  adminPricing,
  adminReports,
  adminCloudSync,
];
