const cashierGettingStarted = {
  id: 'cashier-getting-started',
  name: 'Cashier Getting Started',
  description: 'Complete overview of the Cashier POS panel',
  version: 1,
  portal: 'cashier',
  category: 'Getting Started',
  roles: ['cashier', 'owner', 'admin'],
  requiredModules: [],
  startRoute: null,
  steps: [
    {
      target: '[data-tour="cashier-header"]',
      title: 'Welcome to the Cashier Panel',
      body: 'This is your point-of-sale (POS) system. From here you manage tables, take orders, send KOTs to the kitchen, generate bills, and settle payments. Everything you need to run the front of the house.',
      hint: 'The Cashier panel works on desktop, tablet, and Android devices.',
      placement: 'bottom',
    },
    {
      target: '[data-tour="cashier-tabs"]',
      title: 'Main Sections',
      body: 'The Cashier panel has several main sections: Dashboard (overview and stats), Tables (floor view and table selection), POS (order taking and cart), and Transactions (billing history). Switch between them using the tab buttons.',
      placement: 'bottom',
    },
    {
      target: '[data-tour="cashier-dashboard"]',
      title: 'Dashboard Overview',
      body: 'The dashboard shows today\'s sales summary, table status counts (free vs. occupied), and quick access to key actions. Use this to get a snapshot of how your shift is going.',
      placement: 'bottom',
    },
    {
      target: '[data-tour="cashier-tabs"]',
      title: 'The Complete Cashier Flow',
      body: 'Your daily flow: 1) Select a table from the Tables view. 2) Add items from the menu in POS. 3) Send KOT to the kitchen. 4) When the customer is done, generate the bill. 5) Apply discounts if needed. 6) Take payment (cash/card/UPI/split). 7) Settle and the table becomes free.',
      hint: 'Each of these steps has a dedicated tour. Use the Tour Guide button to explore them.',
      placement: 'bottom',
    },
  ],
};

const cashierTables = {
  id: 'cashier-tables-tour',
  name: 'Cashier Tables Tour',
  description: 'Understand table management, sections, and status',
  version: 1,
  portal: 'cashier',
  category: 'Cashier',
  roles: ['cashier', 'owner', 'admin'],
  requiredModules: [],
  startRoute: null,
  steps: [
    {
      target: '[data-tour="cashier-tables"]',
      title: 'Table Grid',
      body: 'This grid shows all your restaurant\'s tables. Each card shows the table number, current status, and order details if occupied. Click any table to open it — either to take a new order or view an existing one.',
      placement: 'bottom',
    },
    {
      target: '[data-tour="cashier-tables-sections"]',
      title: 'Sections',
      body: 'If your restaurant has multiple sections (Ground Floor, First Floor, Bar, Outdoor), use the section filter to narrow down the table grid. This helps you find tables quickly in large restaurants.',
      hint: 'Section filters are especially useful during busy service hours.',
      placement: 'right',
    },
    {
      target: '[data-tour="cashier-tables"]',
      title: 'Table Status',
      body: 'Each table shows a color-coded status: Free (green — ready for new guests), Occupied (red — has an active order), Preparing (yellow — KOT sent, food being prepared), Waiting Bill (orange — captain requested bill). Click a table to see details.',
      hint: 'Status updates in real-time as captains and kitchen staff update orders.',
      placement: 'bottom',
    },
    {
      target: '[data-tour="cashier-tables"]',
      title: 'Selecting a Table',
      body: 'Click a free table to start a new order — you\'ll be taken to the POS. Click an occupied table to view the active order, add more items, modify the order, or generate the bill. The table you select becomes your active working table.',
      placement: 'bottom',
    },
    {
      target: '[data-tour="cashier-tables"]',
      title: 'Viewing Active Orders',
      body: 'When you click an occupied table, a modal opens showing the active order: all items ordered, their quantities, KOT history, and the running bill total. From here you can add items, cancel items, or proceed to billing.',
      hint: 'The order modal shows real-time data synced from the kitchen and captain.',
      placement: 'bottom',
    },
  ],
};

const cashierPOS = {
  id: 'cashier-pos-tour',
  name: 'Cashier POS Tour',
  description: 'Complete order-taking flow from menu to KOT',
  version: 1,
  portal: 'cashier',
  category: 'Cashier',
  roles: ['cashier', 'owner', 'admin'],
  requiredModules: [],
  startRoute: null,
  steps: [
    {
      target: '[data-tour="cashier-pos"]',
      title: 'POS — Point of Sale',
      body: 'This is where you take orders. The left side shows the menu, the right side shows your cart. Search for items, browse by category, add to cart, and send the KOT to the kitchen.',
      hint: 'The complete flow: Select Table → Find Item → Add to Cart → Send KOT → Generate Bill → Take Payment → Settle.',
      placement: 'bottom',
    },
    {
      target: '[data-tour="cashier-pos-search"]',
      title: 'Finding Menu Items',
      body: 'Use the search bar to quickly find items by name. Or browse by category using the category tabs/filters. You can also filter by dietary type (veg/non-veg) and menu type (food/bar).',
      hint: 'Search is the fastest way to find an item if you know the name.',
      placement: 'bottom',
    },
    {
      target: '[data-tour="cashier-pos-menu"]',
      title: 'Selecting Items',
      body: 'Click any menu item to add it to the cart. Each click adds one quantity. For bar items, you may see quantity options (30ml, 60ml, full bottle). Items that are unavailable (out of stock) are greyed out and cannot be selected.',
      placement: 'right',
    },
    {
      target: '[data-tour="cashier-pos-cart"]',
      title: 'Cart Review',
      body: 'The cart shows all items you\'ve added to the current order. You can adjust quantities, add special notes per item (e.g., "less spicy", "no onion"), and remove items. The cart total updates automatically as you make changes.',
      hint: 'Special notes are printed on the KOT so the kitchen knows the customer\'s preferences.',
      placement: 'left',
    },
    {
      target: '[data-tour="cashier-pos-kot"]',
      title: 'Sending KOT',
      body: 'Click "Send KOT" to send the order to the kitchen. A KOT (Kitchen Order Ticket) is generated with a unique number and printed to the kitchen printer. The kitchen sees the KOT and starts preparing the items.',
      hint: 'Once a KOT is sent, items cannot be removed without a cancellation KOT.',
      placement: 'bottom',
    },
    {
      target: '[data-tour="cashier-pos-cart"]',
      title: 'Continuing the Order',
      body: 'After sending the first KOT, you can continue adding items to the same table. Each new batch of items generates a new KOT. The table\'s complete order accumulates across all KOTs, and the bill reflects everything ordered.',
      placement: 'left',
    },
    {
      target: '[data-tour="cashier-pos-bill"]',
      title: 'Generating the Bill',
      body: 'When the customer is ready to pay, click "Generate Bill" (or "Print Bill"). This creates the final bill with all items, subtotal, taxes (CGST/SGST), discounts, and total amount. The bill is printed to the bill printer.',
      hint: 'You can apply discounts before generating the bill — percentage or flat amount.',
      placement: 'bottom',
    },
    {
      target: '[data-tour="cashier-pos-discount"]',
      title: 'Applying Discounts',
      body: 'Apply a discount before settling: enter a percentage (e.g., 10%) or a flat amount (e.g., ₹50). The discount is applied to the subtotal and the bill recalculates. Discounts are logged in the transaction record for audit.',
      placement: 'bottom',
    },
    {
      target: '[data-tour="cashier-pos-settle"]',
      title: 'Taking Payment & Settlement',
      body: 'After the bill is generated, select the payment method: Cash, Card, UPI, or Split (multiple methods). Enter the amount received, confirm, and the transaction is settled. The table becomes free and ready for the next customer.',
      hint: 'For split payments, enter the amount for each method. The system tracks each portion separately.',
      placement: 'bottom',
    },
  ],
};

const cashierBilling = {
  id: 'cashier-billing-tour',
  name: 'Billing & Payment Tour',
  description: 'Understand bill generation, taxes, payment methods, and settlement',
  version: 1,
  portal: 'cashier',
  category: 'Cashier',
  roles: ['cashier', 'owner', 'admin'],
  requiredModules: [],
  startRoute: null,
  steps: [
    {
      target: '[data-tour="cashier-pos-bill"]',
      title: 'Bill Generation',
      body: 'When you click "Generate Bill", the system calculates: Subtotal (sum of all item prices × quantities), Tax (CGST + SGST based on each item\'s GST rate), Discount (if applied), and Final Total. The bill is printed to the bill printer.',
      placement: 'bottom',
    },
    {
      target: '[data-tour="cashier-pos-bill"]',
      title: 'Subtotal & Taxes',
      body: 'The subtotal is the raw sum of all items before tax and discount. Taxes (CGST + SGST) are applied per item based on its configured GST rate. The bill clearly shows the tax breakdown so the customer can verify.',
      hint: 'GST rates are configured by Admin in Menu Management or Settings.',
      placement: 'bottom',
    },
    {
      target: '[data-tour="cashier-pos-discount"]',
      title: 'Discounts',
      body: 'Apply discounts as a percentage or flat amount. The discount reduces the subtotal before tax calculation (or after, depending on configuration). Discounts are tracked in reports and the audit trail.',
      placement: 'bottom',
    },
    {
      target: '[data-tour="cashier-pos-settle"]',
      title: 'Payment Methods',
      body: 'Choose how the customer pays: Cash (enter amount received, system calculates change), Card (enter card amount), UPI (enter UPI reference), or Split (combine multiple methods). Each method is recorded in the transaction.',
      placement: 'bottom',
    },
    {
      target: '[data-tour="cashier-pos-settle"]',
      title: 'Settlement',
      body: 'Settlement finalizes the transaction. Once settled: the bill is locked, the table becomes free, the transaction is recorded in history, and the sale appears in reports. Settlement is irreversible — use bill edits (Admin only) for corrections.',
      hint: 'Make sure the payment is received before settling. You cannot undo a settlement.',
      placement: 'bottom',
    },
    {
      target: '[data-tour="cashier-pos-settle"]',
      title: 'Receipt / Reprint',
      body: 'After settlement, a receipt is printed. If the customer needs another copy, you can reprint the bill from the Transactions section. The reprinted bill is identical to the original and marked as a reprint.',
      placement: 'bottom',
    },
    {
      target: '[data-tour="cashier-pos-settle"]',
      title: 'What Happens After Settlement',
      body: 'After settlement: 1) Table status changes to Free. 2) Transaction is saved to history. 3) Sale is recorded in reports. 4) Inventory is updated (if recipe mapping is configured). 5) The table is ready for the next customer.',
      placement: 'bottom',
    },
  ],
};

const cashierTransactions = {
  id: 'cashier-transactions-tour',
  name: 'Transactions Tour',
  description: 'View, search, and manage transaction history',
  version: 1,
  portal: 'cashier',
  category: 'Cashier',
  roles: ['cashier', 'owner', 'admin'],
  requiredModules: [],
  startRoute: null,
  steps: [
    {
      target: '[data-tour="cashier-transactions"]',
      title: 'Transaction History',
      body: 'This page shows all transactions processed during your shift. Each entry shows the bill number, table, amount, payment method, and settlement time. Use this to verify your cash drawer and reconcile at end of shift.',
      placement: 'bottom',
    },
    {
      target: '[data-tour="cashier-transactions-list"]',
      title: 'Today\'s Transactions',
      body: 'By default, today\'s transactions are shown. Each row shows the bill number, table number, total amount, payment method (Cash/Card/UPI/Split), and time. Click any transaction to see the full bill details.',
      placement: 'bottom',
    },
    {
      target: '[data-tour="cashier-transactions-list"]',
      title: 'Previous Transactions',
      body: 'Use the date filter to view transactions from previous days. This is useful for investigating past bills, answering customer queries about previous visits, or reconciling end-of-day reports.',
      placement: 'bottom',
    },
    {
      target: '[data-tour="cashier-transactions-list"]',
      title: 'Search & Filters',
      body: 'Search by bill number, table number, or amount. Filter by payment method to count cash vs. card vs. UPI transactions. This helps with end-of-shift cash counting and verifying digital payments.',
      hint: 'At end of shift, filter by "Cash" to see all cash transactions for drawer counting.',
      placement: 'bottom',
    },
    {
      target: '[data-tour="cashier-transactions-list"]',
      title: 'Bill Details & Reprint',
      body: 'Click any transaction to view the full bill: items, quantities, prices, taxes, discounts, and payment breakdown. You can reprint the bill if the customer requests another copy. Reprints are logged.',
      placement: 'bottom',
    },
    {
      target: '[data-tour="cashier-transactions-list"]',
      title: 'Settlement Status',
      body: 'Each transaction shows its settlement status. Settled transactions are final. If a transaction appears as "Pending", it may need attention — check if the payment was completed or if there was an error during settlement.',
      placement: 'bottom',
    },
  ],
};

const cashierSync = {
  id: 'cashier-sync-tour',
  name: 'Cashier Sync Tour',
  description: 'Understand offline behavior and sync status in simple terms',
  version: 1,
  portal: 'cashier',
  category: 'Cloud Sync',
  roles: ['cashier', 'owner', 'admin'],
  requiredModules: [],
  startRoute: null,
  steps: [
    {
      target: '[data-tour="sync-status"]',
      title: 'Sync Status',
      body: 'The sync indicator shows your connection status. Green means you\'re online and everything is synced. Yellow or red means you\'re offline — but you can keep working! All your orders and bills are saved locally and will sync automatically.',
      hint: 'Don\'t worry if the indicator turns yellow — the POS keeps working normally.',
      placement: 'bottom',
    },
    {
      target: '[data-tour="sync-status"]',
      title: 'Offline Actions',
      body: 'When you\'re offline, everything you do — taking orders, sending KOTs, generating bills, settling payments — is saved on this device. Nothing is lost. You can continue serving customers normally.',
      placement: 'bottom',
    },
    {
      target: '[data-tour="sync-status"]',
      title: 'Pending Actions',
      body: 'The sync indicator may show a count of pending actions — these are orders and bills waiting to be uploaded. This number goes down as actions are synced. If it stays high, check your internet connection.',
      hint: 'A high pending count for a long time may indicate a connection problem.',
      placement: 'bottom',
    },
    {
      target: '[data-tour="sync-status"]',
      title: 'When Internet Comes Back',
      body: 'When your connection is restored, the system automatically uploads all pending orders and bills to the cloud. You don\'t need to do anything — it happens in the background. The indicator will turn green when everything is synced.',
      hint: 'You\'ll see the indicator change from yellow → "Syncing" → green.',
      placement: 'bottom',
    },
    {
      target: '[data-tour="sync-status"]',
      title: 'What to Do If Sync Is Pending',
      body: 'If sync seems stuck: 1) Check your internet connection. 2) Wait a minute — large batches take time. 3) If it persists, ask your manager to check the sync status in Admin. 4) Never delete browser data or clear cache while pending — this could lose unsynced orders.',
      hint: 'When in doubt, keep taking orders. The system will sync when it can.',
      placement: 'bottom',
    },
  ],
};

export default [
  cashierGettingStarted,
  cashierTables,
  cashierPOS,
  cashierBilling,
  cashierTransactions,
  cashierSync,
];
