export default {
  id: 'cloud-sync-overview',
  name: 'Cloud Sync Overview',
  description: 'How data flows between Admin, Cashier, and Captain',
  version: 1,
  portal: 'admin',
  category: 'Cloud Sync',
  roles: ['admin', 'owner', 'manager', 'cashier', 'captain'],
  requiredModules: [],
  startRoute: null,
  steps: [
    {
      target: null,
      title: 'How Softshape Sync Works',
      body: 'Softshape uses an offline-first architecture. This means every panel — Admin, Cashier, and Captain — works even without internet. Data is saved locally first, then synced to the cloud when connectivity is available.',
      hint: 'This design ensures your restaurant never stops operating, regardless of internet status.',
      placement: 'bottom',
    },
    {
      target: null,
      title: 'Admin → Cloud → Cashier & Captain',
      body: 'When Admin makes changes (menu, tables, staff, printers, pricing): 1) Changes are saved to the local edge server (SQLite). 2) The sync engine pushes changes to the cloud. 3) Cashier and Captain devices pull updates or receive them via WebSocket when online.',
      placement: 'bottom',
    },
    {
      target: null,
      title: 'Cashier/Captain → Cloud → Admin',
      body: 'When Cashier or Captain take actions (orders, KOTs, settlements): 1) Actions are saved locally in IndexedDB. 2) When online, actions are replayed to the cloud via the sync engine. 3) Admin sees the results in real-time on the dashboard and reports.',
      placement: 'bottom',
    },
    {
      target: '[data-tour="sync-status"]',
      title: 'Sync Status Indicator',
      body: 'The sync status indicator shows your current state: Online (green — all data synced), Offline (yellow — working locally, actions queued), Syncing (uploading pending actions). Always check this indicator if something seems out of date.',
      hint: 'If the indicator is yellow, you\'re offline but can keep working. Everything will sync when internet returns.',
      placement: 'bottom',
    },
    {
      target: null,
      title: 'What Data Syncs',
      body: 'Menu items (add, edit, price, availability), table configurations, staff accounts, orders, KOTs, settlements, transactions, and restaurant settings all sync through the cloud. The sync engine handles conflicts gracefully and logs them for resolution.',
      placement: 'bottom',
    },
    {
      target: null,
      title: 'Offline Behavior',
      body: 'When offline: 1) All panels continue working with local data. 2) Orders, KOTs, and settlements are stored locally. 3) Menu and table data from the last sync remains available. 4) No data is lost — everything is queued for automatic sync.',
      placement: 'bottom',
    },
    {
      target: null,
      title: 'When Internet Returns',
      body: 'When connectivity is restored: 1) The sync engine automatically replays all queued actions. 2) Conflicts are flagged for resolution if needed. 3) Cloud data is pulled to update local caches. 4) WebSocket reconnects for real-time updates. 5) The sync indicator turns green when complete.',
      hint: 'Sync is fully automatic — you never need to manually trigger it.',
      placement: 'bottom',
    },
    {
      target: null,
      title: 'Important: No Real-Time Config Sync',
      body: 'Configuration changes (menu, tables, settings) are NOT pushed in real-time to offline devices. They sync when the device comes online and pulls updates. However, operational data (orders, table status) IS pushed in real-time via WebSocket when all devices are online.',
      hint: 'If a Cashier doesn\'t see your menu changes, they may be offline. They\'ll get the update when they reconnect.',
      placement: 'bottom',
    },
  ],
};
