export default {
  id: 'landing-tour',
  name: 'Softshape Product Tour',
  description: 'Learn what Softshape is and how it helps your restaurant',
  version: 1,
  portal: 'landing',
  category: 'Landing',
  roles: [],
  requiredModules: [],
  startRoute: null,
  steps: [
    {
      target: '[data-tour="landing-hero"]',
      title: 'Welcome to Softshape',
      body: 'Softshape is a complete restaurant management platform that handles everything from billing and orders to inventory, staff, and reports — all in one place.',
      hint: 'This tour will walk you through the entire product. You can skip at any time.',
      placement: 'bottom',
    },
    {
      target: '[data-tour="landing-hero"]',
      title: 'The Problem Softshape Solves',
      body: 'Restaurants juggle billing, order taking, kitchen communication, inventory, staff management, and reporting across multiple devices. Softshape unifies all of this into a single, connected system that works online and offline.',
      placement: 'bottom',
    },
    {
      target: '[data-tour="landing-portal-admin"]',
      title: 'Admin Panel',
      body: 'The Admin Panel is where you configure your restaurant. Manage your menu, tables, staff, printers, pricing, inventory, purchases, and view detailed reports. This is the control center for your entire operation.',
      hint: 'Admin is used by owners and managers to set up and monitor the restaurant.',
      placement: 'right',
    },
    {
      target: '[data-tour="landing-portal-cashier"]',
      title: 'Cashier Panel',
      body: 'The Cashier Panel is the point-of-sale (POS) used for billing. Cashiers select tables, take orders, send KOTs to the kitchen, generate bills, apply discounts and taxes, and settle payments — by cash, card, UPI, or split payment.',
      hint: 'Cashier works on desktop, tablet, and Android devices.',
      placement: 'right',
    },
    {
      target: '[data-tour="landing-portal-captain"]',
      title: 'Captain Panel',
      body: 'The Captain Panel is used by waiters/captains to take orders at the table. Captains select a table, browse the menu, add items to the cart, and send KOTs directly to the kitchen — all from their phone.',
      hint: 'Captain works on Android phones and tablets.',
      placement: 'left',
    },
    {
      target: '[data-tour="landing-portals"]',
      title: 'How the Panels Work Together',
      body: 'Admin configures the menu, tables, and settings. Cashier and Captain use that configuration to take orders and process payments. Changes made in Admin are synchronized to Cashier and Captain through the cloud sync layer.',
      hint: 'The flow is: Admin → Cloud Sync → Cashier & Captain',
      placement: 'top',
    },
    {
      target: '[data-tour="landing-hero"]',
      title: 'Cloud-Based Synchronization',
      body: 'Softshape uses an offline-first architecture. All panels work even without internet. When connectivity returns, actions are automatically synced to the cloud. This means your restaurant never stops, even during network outages.',
      hint: 'Orders, KOTs, and settlements are queued locally and replayed when the connection is restored.',
      placement: 'bottom',
    },
    {
      target: '[data-tour="landing-hero"]',
      title: 'From Setup to Daily Operations',
      body: 'The journey is simple: 1) Sign up and onboard your restaurant. 2) Configure menu, tables, printers, and staff in Admin. 3) Cloud sync pushes settings to Cashier and Captain. 4) Captains take orders, Cashiers handle billing. 5) Admin monitors everything via reports.',
      placement: 'bottom',
    },
    {
      target: '[data-tour="landing-get-started"]',
      title: 'Get Started',
      body: 'Ready to begin? Click "Get Started" to create your restaurant account and start the onboarding process. The onboarding wizard will guide you through setting up your restaurant step by step.',
      hint: 'You can also explore the portals above to see what each one looks like.',
      placement: 'top',
    },
  ],
};
