export default {
  id: 'onboarding-tour',
  name: 'Restaurant Onboarding Guide',
  description: 'Step-by-step guide to setting up your restaurant',
  version: 1,
  portal: 'onboarding',
  category: 'Onboarding',
  roles: [],
  requiredModules: [],
  startRoute: '/onboarding',
  steps: [
    {
      target: '[data-tour="onboarding-wizard"]',
      title: 'Welcome to Restaurant Onboarding',
      body: 'This wizard will guide you through setting up your restaurant in Softshape. Each step collects information that your restaurant needs to operate. You can change most of this later, but some fields are required before you can start serving customers.',
      hint: 'Follow each step in order. The progress bar shows how far along you are.',
      placement: 'right',
    },
    {
      target: '[data-tour="onboarding-step-restaurant"]',
      title: 'Restaurant Information',
      body: 'Enter your restaurant\'s name, type (dining, bar, café, etc.), and contact details. This information appears on your bills, receipts, and reports. Your restaurant type determines which features are available (e.g., bar venues get liquor inventory).',
      hint: 'You can change your restaurant name and contact info later in Settings.',
      placement: 'right',
    },
    {
      target: '[data-tour="onboarding-step-owner"]',
      title: 'Owner / Business Information',
      body: 'Provide the owner\'s name, phone number, and email. This is used for account recovery, billing notifications, and important updates. The owner has full access to all panels and settings.',
      hint: 'Make sure the phone number is correct — it\'s used for login and OTP verification.',
      placement: 'right',
    },
    {
      target: '[data-tour="onboarding-step-outlet"]',
      title: 'Outlet / Restaurant Setup',
      body: 'Configure your outlet details: address, GST number, number of venues/outlets, and operating hours. If you have multiple outlets, each gets its own configuration. GST is required for tax calculations on bills.',
      hint: 'GST number can be added later, but is needed before generating GST-compliant bills.',
      placement: 'right',
    },
    {
      target: '[data-tour="onboarding-step-staff"]',
      title: 'Staff Setup',
      body: 'Add your captains (waiters) and cashiers. Each staff member gets a PIN for login. Captains take orders at tables, cashiers handle billing and payments. You can add more staff later in Admin → Staff.',
      hint: 'Staff PINs are used for quick login on shared devices.',
      placement: 'right',
    },
    {
      target: '[data-tour="onboarding-step-menu"]',
      title: 'Menu Setup',
      body: 'Create your menu by adding categories (Starters, Main Course, Beverages, etc.) and items within each category. Each item has a name, price, dietary type (veg/non-veg), and optional GST rate. This menu will be available to Cashier and Captain after sync.',
      hint: 'You can also bulk-import menu items or use AI menu parsing later in Admin → Menu.',
      placement: 'right',
    },
    {
      target: '[data-tour="onboarding-step-tax"]',
      title: 'Taxes / GST Configuration',
      body: 'Set up your tax rates — CGST, SGST, or a single GST percentage. These rates are applied automatically when generating bills. You can configure different tax rates for different item categories.',
      hint: 'Tax rates can be adjusted later in Admin → Settings → Tax Configuration.',
      placement: 'right',
    },
    {
      target: '[data-tour="onboarding-step-tables"]',
      title: 'Tables & Sections',
      body: 'Create sections (e.g., Ground Floor, First Floor, Outdoor) and add tables to each section. Tables are numbered and used by Cashier and Captain to manage orders. Each table can have a QR code for digital ordering.',
      hint: 'Tables and sections can be reconfigured anytime in Admin → Tables.',
      placement: 'right',
    },
    {
      target: '[data-tour="onboarding-step-printers"]',
      title: 'Printer Configuration',
      body: 'Set up your kitchen printer (for KOTs), bar printer (for bar orders), and bill printer (for customer bills). You can map which items go to which printer. Without printer setup, KOTs and bills can only be viewed on screen.',
      hint: 'Printers can be configured later in Admin → Printers. You can also use digital KOTs without a printer.',
      placement: 'right',
    },
    {
      target: '[data-tour="onboarding-step-branding"]',
      title: 'Branding',
      body: 'Upload your restaurant logo and customize the colors that appear on your bills, KOTs, and the app interface. Your branding makes your receipts look professional and consistent.',
      hint: 'Branding can be updated anytime in Admin → Settings → Branding.',
      placement: 'right',
    },
    {
      target: '[data-tour="onboarding-step-plan"]',
      title: 'Subscription / Plan',
      body: 'Choose your Softshape subscription plan. Different plans unlock different features and support levels. You start with a free trial, so you can explore everything before committing.',
      hint: 'You can upgrade or change your plan anytime in Admin → Settings → Billing.',
      placement: 'right',
    },
    {
      target: '[data-tour="onboarding-step-confirm"]',
      title: 'Final Confirmation',
      body: 'Review all the information you\'ve entered. Make sure everything is correct before confirming. After confirmation, your restaurant is created and you\'ll be taken to the Admin Panel to start configuring your operations.',
      hint: 'Don\'t worry — almost everything can be changed later in Admin Settings.',
      placement: 'right',
    },
    {
      target: '[data-tour="onboarding-wizard"]',
      title: 'What Happens After Onboarding',
      body: 'Once onboarding is complete, you\'ll enter the Admin Panel. From there: configure your menu in detail, set up printers, add staff, and then sync everything to Cashier and Captain. A getting-started tour will guide you through the Admin Panel automatically.',
      hint: 'The flow is: Onboarding → Admin Configuration → Cloud Sync → Cashier & Captain ready for operations.',
      placement: 'right',
    },
  ],
};
